### ISSUE TITLE
Multiple lines per sample using linegraph.plot

### ISSUE THREAD

**Issue by cvdelannoy** [ewels/MultiQC#696] opened 2018-03-02 15:16 UTC
`scatter.plot()` allows multiple points per sample, by providing a list of dicts. The same functionality does not exist for `linegraph.plot()`, but I would very much like that for some custom modules I'm working on (e.g. one for mummerplots).

**Comment by ewels** [comment] 2018-03-04 19:06
Hi @cvdelannoy,

This is partly by design. Could you explain why you want multiple lines per sample?

In other modules I've just made multiple "samples" per sample for the plot. eg. `sample1-A`, `sample1-B`, `sample2-A`, `sample2-B` etc.

Phil

**Comment by cvdelannoy** [comment] 2018-03-05 13:06
Hi Phil,
Oh that would be a solution as well! Although then you can't easily create buttons to switch between sets of lines that belong together, right?

I wanted to give an impression of what the alignment by nucmer looked like in the report, by parsing the *.fplot and *.rplot files it produces. These contain start and end coordinates of aligned parts in each alignment, so per alignment that means several lines. I managed to render it with scatterplot however! 
![multiqc_mummerplot](https://user-images.githubusercontent.com/21309905/36976374-abe13768-207d-11e8-8edb-f55cc34bedea.png)

It's kinda heavy though, as every line now consists of many points, so I'm guessing not really suitable for core implementation (it's pretty fine for my purposes). Perhaps this would be feasible for core if I could plot it with lines? If there is interest in a module that produces synteny plots, that is.

Carlos

**Comment by ewels** [comment] 2018-03-20 13:34
> Although then you can't easily create buttons to switch between sets of lines that belong together, right?

Yes you can (see [docs](http://multiqc.info/docs/#switching-datasets-1)) - unless I'm misunderstanding you?

Then you could have one "dataset" button per actual sample, then each one can have multiple lines... This wouldn't scale very well to lots of samples, but I guess for this application it's fairly unlikely to have large numbers of samples..?

NB: Lots of data is generally bad. If these are always straight lines, it should be fine to take just the first and last data point I guess?

Phil

**Comment by ewels** [comment] 2018-04-18 15:59
Closing this issue for now. Shout if there's anything else I can help with!

**Closed by ewels** 2018-04-18 15:59 UTC
Labels: question

**Comment by cvdelannoy** [comment] 2018-04-20 12:42
Sorry for the delay, yeah that would do!

**Comment by ewels** [comment] 2018-04-20 12:56
Note that the same request has come up in a few other issues for different reasons, so this will probably be implemented :) But I think that a line plot with multiple dataset tabs is still probably the best route for you here..

xref https://github.com/ewels/MultiQC/issues/695
