### ISSUE TITLE
Duplicate sample name found!

### ISSUE THREAD

**Issue by avenise** [ewels/MultiQC#887] opened 2019-01-15 15:15 UTC
I have two samples' fastqc results in the same folder and tried the MultiQC version 1.7 to generate the report. The files in the folder are called 
```
140702_SN700173R_0668_AC4LHVACXX_SB635261_ATGCCTAA_L008_R2_001_HQ_paired_fastqc.html
140702_SN700173R_0668_AC4LHVACXX_SB635261_ATGCCTAA_L008_R2_001_HQ_paired_fastqc.zip
141015_SN7001343_0160_BC5GDMACXX_SB635261_ATGCCTAA_L008_R2_001_HQ_paired_fastqc.html
141015_SN7001343_0160_BC5GDMACXX_SB635261_ATGCCTAA_L008_R2_001_HQ_paired_fastqc.zip
```

The command I used to run is 
```
multiqc -s -d .
```

However, Multiqc only generate one sample's html report and it says:
```
Duplicate sample name found! Overwriting: SB635261_ATGCCTAA_L008_R2_001_HQ_paired.fastq.gz"
```
in the `multiqc.log` file.

I need multiqc to generate the two samples' report instead of overwriting the sample. Anybody can help? Thank you in advance!

**Comment by ewels** [comment] 2019-01-23 21:57
This is because FastQC sample names are based on the input file that was used and reported in the FastQC report, _not_ the filename of the FastQC report itself.

This issue is a duplicate of #890, so closing and will continue work on the other issue.

**Closed by ewels** 2019-01-23 21:57 UTC
