### ISSUE TITLE
Oops! The 'qorts' MultiQC module broke...

### ISSUE THREAD

**Issue by nickluscombe** [ewels/MultiQC#821] opened 2018-08-30 15:44 UTC
```
$ multiqc --ignore ERR* --dirs QoRTs_output/ --filename multiQC_align
[INFO   ]         multiqc : This is MultiQC v1.6
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Prepending directory to sample names
[INFO   ]         multiqc : Searching 'QoRTs_output/'
Searching 34 files..  [####################################]  100%
[ERROR  ]         multiqc : Oops! The 'qorts' MultiQC module broke...
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues
  If possible, please include a log file that triggers the error - the last file found was:
    QoRTs_output/QC.summary.txt
============================================================
Module qorts raised an exception: Traceback (most recent call last):
  File "/Users/luscomn/anaconda3/envs/bioinfo/bin/multiqc", line 440, in multiqc
    output = mod()
  File "/Users/luscomn/anaconda3/envs/bioinfo/lib/python3.5/site-packages/multiqc/modules/qorts/qorts.py", line 30, in __init__
    self.parse_qorts(f)
  File "/Users/luscomn/anaconda3/envs/bioinfo/lib/python3.5/site-packages/multiqc/modules/qorts/qorts.py", line 68, in parse_qorts
    self.qorts_data[s_name][s[0]] = float(s[i+1])
ValueError: could not convert string to float: 'Code for the strandedness rule used. 0 if data is unstranded, 1 if data is fr_firstStrand, 2 if data is fr_secondStrand.\n'
============================================================
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete
```
(bioinfo)
[QC.summary.txt](https://github.com/ewels/MultiQC/files/2336840/QC.summary.txt)

**Comment by ewels** [comment] 2018-10-08 16:53
Hi @nickluscombe,

Sorry it's taken me so long to get to this. Now I'm here, I'm pretty confused though. When I run MultiQC with your file, it works fine without any errors. Looking at the code history, your error looks basically identical to #639 - this was fixed in https://github.com/ewels/MultiQC/commit/62fe08930442b5454f68686910df0adc86cc46c4 back in December, which went out in MultiQC v1.4.

Your log says that you're running MultiQC 1.6, so it _should_ be fine if it's the same problem. How do you have MultiQC installed? Is there something strange going on with your installation? My first port of call would be to try reinstalling.

Phil

**Comment by ewels** [comment] 2018-12-21 15:41
Closing as I cannot reproduce the error.

**Comment by jkokosar** [comment] 2019-02-22 13:50
@ewels I've bumped into the same issue. The problem seem to be the `parse_qorts()` not properly handling the use of `--dirs` parameter.

**Comment by ewels** [comment] 2019-02-25 11:25
Thanks @jkokosar - do you have a file I can reproduce this with? I don't get the same error, even with basically the exact command used above:

```
$ ls
QC.summary.txt

$ multiqc --ignore ERR* --dirs . --filename multiQC_align
[INFO   ]         multiqc : This is MultiQC v1.7.dev0 (12f519c)
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Prepending directory to sample names
[INFO   ]         multiqc : Searching '.'
Searching 1 files..  [####################################]  100%
[INFO   ]           qorts : Found 1 logs
[INFO   ]         multiqc : Compressing plot data
[INFO   ]         multiqc : Report      : multiQC_align.html
[INFO   ]         multiqc : Data        : multiQC_align_data
[INFO   ]         multiqc : MultiQC complete
```

**Comment by jkokosar** [comment] 2019-02-25 14:05
@ewels you can use the file already attached to the issue - just add it to a subfolder, one level down from where you make a multiqc call.

```
(multiqc) mac qorts$ ls
example_folder
(multiqc) mac qorts$ ls example_folder/
QC.summary.txt
(multiqc) mac qorts$ multiqc --ignore ERR* --dirs . --filename multiQC_align
[INFO   ]         multiqc : This is MultiQC v1.7
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Prepending directory to sample names
[INFO   ]         multiqc : Searching '.'
[ERROR  ]         multiqc : Oops! The 'qorts' MultiQC module broke...
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues
  If possible, please include a log file that triggers the error - the last file found was:
    ./example_folder/QC.summary.txt
============================================================
Module qorts raised an exception: Traceback (most recent call last):
  File "/Users/janez/virtualenvs/multiqc/bin/multiqc", line 440, in multiqc
    output = mod()
  File "/Users/janez/virtualenvs/multiqc/lib/python3.7/site-packages/multiqc/modules/qorts/qorts.py", line 30, in __init__
    self.parse_qorts(f)
  File "/Users/janez/virtualenvs/multiqc/lib/python3.7/site-packages/multiqc/modules/qorts/qorts.py", line 68, in parse_qorts
    self.qorts_data[s_name][s[0]] = float(s[i+1])
ValueError: could not convert string to float: 'Code for the strandedness rule used. 0 if data is unstranded, 1 if data is fr_firstStrand, 2 if data is fr_secondStrand.\n'
============================================================
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete
```

**Comment by ewels** [comment] 2019-02-25 14:05
Ahhh, I didn't have it in a subfolder - thanks! 👍

**Comment by ewels** [comment] 2019-03-08 17:25
Hi all,

This should now work in the latest v1.8dev of MultiQC. If you could give it a spin to confirm that would be great.. Thanks!

Phil

**Closed** 2019-03-08 17:25 UTC
Labels: bug

**Comment by jkokosar** [comment] 2019-03-10 17:01
Works for me! Thank you!

**Comment by hreinwal** [comment] 2019-07-30 13:48
Hi Phil, 
I am using MultiQC 1.7 and qorts 1.3.0 and I just ran in the same error message as posted above. Thanks for making such a quick fix - however I am having problems installing Multiqc 1.8 via conda. 
Could you provide some guidelines on how to get the 1.8dev version to run? 

Best,
Hannes

**Comment by sdjebali** [comment] 2021-09-03 12:27
Dear all,
I am having the same error with `multiqc 1.9` when I run the nf core atacseq pipeline with very lowly sequenced data

here is the trace that follows the error
```
    If possible, please include a log file that triggers the error - the last file found was:
       ./deeptools/liver_R138.mLb.clN.plotProfile.tab
 ============================================================
   Module deeptools raised an exception: Traceback (most recent call last):
    File "/opt/conda/envs/nf-core-atacseq-1.2.1/lib/python3.7/site-packages/multiqc/multiqc.py", line 569, in run
      output = mod()
    File "/opt/conda/envs/nf-core-atacseq-1.2.1/lib/python3.7/site-packages/multiqc/modules/deeptools/deeptools.py", line 74, in __init__
      n['plotProfile'] = self.parse_plotProfile()
    File "/opt/conda/envs/nf-core-atacseq-1.2.1/lib/python3.7/site-packages/multiqc/modules/deeptools/plotProfile.py", line 17, in parse_plotProfile
      parsed_data, bin_labels, converted_bin_labels = self.parsePlotProfileData(f)
    File "/opt/conda/envs/nf-core-atacseq-1.2.1/lib/python3.7/site-packages/multiqc/modules/deeptools/plotProfile.py", line 111, in parsePlotProfileData
      d[s_name].update({converted_bin_labels[i-1]:float(cols[i+1])})
  ValueError: could not convert string to float: '--'
  ============================================================
  [INFO   ]        samtools : Found 2 stats reports
  [INFO   ]        samtools : Found 2 flagstat reports
  [INFO   ]        samtools : Found 2 idxstats reports
  [INFO   ]          picard : Found 2 MarkDuplicates reports
  [INFO   ]         multiqc : Compressing plot data
  [INFO   ]         multiqc : Report      : multiqc_report.html
  [INFO   ]         multiqc : Data        : multiqc_data
  [INFO   ]         multiqc : MultiQC complete

```
As I understand the ` ./deeptools/liver_R138.mLb.clN.plotProfile.tab` file (that I cannot attach here because its format is not supported) has` -- `strings that cannot be converted to floats. It may be due to the fact that this samples has very very few reads but it would be good not to have a complete fail of the pipeline for this reason ?

Let me know if this is not the right place to post this issue.

Thanks,
