### ISSUE TITLE
qualimap module can't find files

### ISSUE THREAD

**Issue by tjthurman** [ewels/MultiQC#392] opened 2017-01-27 22:55 UTC
Hi,

Thanks for the great tool, it's been perfect for compiling FastQC reports across many samples, but I've had some problems compiling reports from the BamQC tool in qualimap: sometimes MultiQC works, and sometimes it can't find the log files produced by qualimap.  Some files are successfully detected when I run MultiQC on a HPC cluster, but aren't detected when I run MultiQC on my local machine, and others aren't detected no matter the machine I'm using. I'm not sure if this is caused by a problem with the way I'm using qualimap, but I'm not seeing any obvious differences in the format or naming of the results files that work and those that don't.

When working on a cluster with MultiQC version 0.8, if MultiQC fails it doesn't throw any errors, but simply reports that no analysis results were found. On my machine (Mac OS X 10.11.6) with MultiQC version 0.9 (installed with conda), MultiQC gives the error pasted below.

I've attached .zip archive of results from 2 different runs of qualimap's BamQC tool. The "A" results don't work on the cluster or my machine: on the cluster they simply aren't found, with no errors, while on my machine they throw the error below. The "B" results work fine on the cluster, but give the error below on my machine. Please let me know if there's any other info I can provide to help sort out the issue.

Thanks!

```
[INFO   ]         multiqc : This is MultiQC v0.9
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching '.'
[ERROR  ]         multiqc : Oops! The 'qualimap' MultiQC module broke... 
                    Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
                    (if possible, include a log file that triggers the error) 
============================================================
Module qualimap raised an exception: Traceback (most recent call last):
  File "/Users/tthurman/miniconda3/lib/python3.5/site-packages/multiqc-0.9-py3.5.egg/EGG-INFO/scripts/multiqc", line 344, in multiqc
    output = mod()
  File "/Users/tthurman/miniconda3/lib/python3.5/site-packages/multiqc-0.9-py3.5.egg/multiqc/modules/qualimap/qualimap.py", line 40, in __init__
    n['BamQC'] = QM_BamQC.parse_reports(self)
  File "/Users/tthurman/miniconda3/lib/python3.5/site-packages/multiqc-0.9-py3.5.egg/multiqc/modules/qualimap/QM_BamQC.py", line 54, in parse_reports
    report_sections(self)
  File "/Users/tthurman/miniconda3/lib/python3.5/site-packages/multiqc-0.9-py3.5.egg/multiqc/modules/qualimap/QM_BamQC.py", line 324, in report_sections
    'extra_series': extra_series,
  File "/Users/tthurman/miniconda3/lib/python3.5/site-packages/multiqc-0.9-py3.5.egg/multiqc/plots/linegraph.py", line 89, in plot
    elif type(pconfig['extra_series']) == list and type(pconfig['extra_series'][0]) == dict:
IndexError: list index out of range
============================================================
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete
```
[qualimap_res_A.zip](https://github.com/ewels/MultiQC/files/736426/qualimap_res_A.zip)
[qualimap_res_B.zip](https://github.com/ewels/MultiQC/files/736425/qualimap_res_B.zip)

**Comment by mjmontague** [comment] 2017-01-30 18:43
I'm having similar (but not identical) issues with Bam QC output. I moved all the summary text files from Qualimap into a single directory (from ~200 samples):

[INFO   ]         multiqc : This is MultiQC v1.0.dev0
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching '.'
UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete

I've never seen this warning with other runs of MultiQC:
UserWarning: Matplotlib is building the font cache using fc-list

**Comment by ewels** [comment] 2017-01-30 19:39
Hi @tjthurman, sorry you're having problems and thanks for the detailed bug report (plus input files). I'm away at the moment but will look into this fully when I'm back in a few weeks.

@mjmontague - the warning you're seeing is from Matplotlib, a package that MultiQC uses. It's nothing to worry about and won't affect how MultiQC runs. However, moving all of the summary files into a single directory will stop MultiQC from finding reports as for Qualimap it depends on directory structure (long story, but basically it uses multiple text files and not all of them have sample names contained).

Hope this helps!

Phil

**Comment by mjmontague** [comment] 2017-01-30 19:46
@ewels thanks for the instructions - I'll run MutliQC from the original parent directory

**Comment by mjmontague** [comment] 2017-02-01 20:51
@ewels MultiQC still can't find any bamqc analysis results. What exactly is it looking for?

For a single sample, I have these files in the main analysis directory:
.
├── css
│   ├── agogo.css
│   ├── ajax-loader.gif
│   ├── basic.css
│   ├── bgfooter.png
│   ├── bgtop.png
│   ├── comment-bright.png
│   ├── comment-close.png
│   ├── comment.png
│   ├── doctools.js
│   ├── down.png
│   ├── down-pressed.png
│   ├── file.png
│   ├── jquery.js
│   ├── minus.png
│   ├── plus.png
│   ├── pygments.css
│   ├── qualimap_logo_small.png
│   ├── report.css
│   ├── searchtools.js
│   ├── underscore.js
│   ├── up.png
│   ├── up-pressed.png
│   └── websupport.js
├── genome_results.txt
├── images_qualimapReport
│   ├── genome_coverage_0to50_histogram.png
│   ├── genome_coverage_across_reference.png
│   ├── genome_coverage_histogram.png
│   ├── genome_coverage_quotes.png
│   ├── genome_gc_content_per_window.png
│   ├── genome_homopolymer_indels.png
│   ├── genome_insert_size_across_reference.png
│   ├── genome_insert_size_histogram.png
│   ├── genome_mapping_quality_across_reference.png
│   ├── genome_mapping_quality_histogram.png
│   ├── genome_reads_clipping_profile.png
│   ├── genome_reads_content_per_read_position.png
│   └── genome_uniq_read_starts_histogram.png
├── qualimapReport.html
└── raw_data_qualimapReport
    ├── coverage_across_reference.txt
    ├── coverage_histogram.txt
    ├── duplication_rate_histogram.txt
    ├── genome_fraction_coverage.txt
    ├── homopolymer_indels.txt
    ├── insert_size_across_reference.txt
    ├── insert_size_histogram.txt
    ├── mapped_reads_clipping_profile.txt
    ├── mapped_reads_gc-content_distribution.txt
    ├── mapped_reads_nucleotide_content.txt
    ├── mapping_quality_across_reference.txt
    └── mapping_quality_histogram.txt

All were output by bamqc using the default command

**Comment by ewels** [comment] 2017-02-01 21:15
@mjmontague - maybe don't run MultiQC from inside the folder? It might need the directory name or something. Sorry for the vague answers, this is from my (poor) memory on my iPhone - I'll have a proper look into this and write some docs when I'm back in a few weeks. You're not the first person to run into difficulties so it needs some explanation for sure!

Phil

**Comment by ewels** [comment] 2017-02-23 11:26
Hi @mjmontague,

I've had another look at the files you have above and it looks fine. My guess is that you need to move up a directory before running MultiQC before it will work. You can see the exact files that MultiQC searches for [here](https://github.com/ewels/MultiQC/blob/master/multiqc/utils/search_patterns.yaml#L101-L112) and the test datasets that I use for Qualimap [here](https://github.com/ewels/MultiQC_TestData/tree/master/data/modules/qualimap/bam_qc). If you try this and it's still not working, please send me the files and I'll try to replicate the problem myself.

Phil

**Comment by ewels** [comment] 2017-02-23 14:26
Hi @tjthurman,

#### qualimap_res_A
I've tried running your example reports and have made some progress.. First I tried the `qualimap_res_A.zip` files. I got the same as you - nothing was found and MultiQC exited without creating a report. I re-ran MultiQC in verbose mode (`-v`) to see the detailed log and noticed these lines in particular:
```
[2017-02-23 12:23:18,125] multiqc  [DEBUG  ]  Ignoring file as too large: genome_results.txt
[2017-02-23 12:23:18,126] multiqc  [DEBUG  ]  Ignoring file as too large: qualimapReport.html
```

When MultiQC is scanning available files, it makes guesses about which are log files and what is likely to be just data. For example, it skips binary files, but it also skips large files (eg. FastQ files). The default filesize limit is 10MB - your qualimap files were larger than this, so MultiQC ignored them.

I created a new MultiQC config file in the directory where I was running to change this default, as follows (500MB instead):
```yaml
log_filesize_limit: 500000000
```

Now MultiQC runs and finds your report as expected:
```
[INFO   ]         multiqc : This is MultiQC v1.0.dev0 (eba1b03)
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching '.'
[INFO   ]        qualimap : Found 1 BamQC reports
[INFO   ]         multiqc : Report      : multiqc_report.html
[INFO   ]         multiqc : Data        : multiqc_data
[INFO   ]         multiqc : MultiQC complete
```

I looked into your files to try to work out why they are so big (they're [usually](https://github.com/ewels/MultiQC_TestData/blob/master/data/modules/qualimap/bam_qc/ERR089819.qc/genome_results.txt) only a few kb). It seems that your reference genome has a very large number of contigs. Instead of the 128 lines in `genome_results.txt` that I've previously seen for Human samples, yours has 270269.. ;)

So, to fix this problem you just need to [change your MultiQC configuration](http://multiqc.info/docs/#configuring-multiqc) to allow larger files.

#### qualimap_res_A
This second file is trickier as I couldn't reproduce the error. I ran the files and it worked fine. So this is hopefully good news - if you update to the latest version of MultiQC it should work. I've also dug into the code based on the traceback that you pasted and added an extra exception class to try to catch that error if it does occur again (it should be harmless). 

I hope this helps! I'll close this issue now, but please do reopen if you run into any further problems or have any questions.

Cheers,

Phil

**Closed** 2017-02-23 14:27 UTC
Labels: bug

**Comment by tjthurman** [comment] 2017-02-23 19:34
Hi @ewels,

Thanks so much, increasing the file size limit did the trick! Yes, I'm working with the preliminary genome of a non-model organism, which is why I have such an outrageous number of contigs. Thanks for the help, and the awesome tool!

Best,
Tim
