### ISSUE TITLE
not presenting the real number of reads

### ISSUE THREAD

**Issue by cyadrogarcia** [ewels/MultiQC#1907] opened 2023-04-21 19:00 UTC
### Description of bug

Hi I have detected that the number of reads reported in the summary and in the graphs is not correct. Apparently MULTIQC  is only reporting one of the number of reads, wether is it forward or reverse sequence but it juts take the number of reads from one of them and use it for both

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/#troubleshooting-1).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by ewels** [comment] 2023-09-23 08:00
Please say which module this is. Provide example data showing what the problem is. There is not enough information in this issue to reproduce the problem.

Closing as this is quite old, please create a new issue using the issue template for bugs if this is still a problem, and complete all fields.

**Closed by ewels** 2023-09-23 08:00 UTC
