### ISSUE TITLE
snpeff stats not being picked up

### ISSUE THREAD

**Issue by ramaniak** [ewels/MultiQC#229] opened 2016-06-01 17:03 UTC
[S1_ILLUMINA.merge.dedup.realign.recal.snpeff.stats.summary.txt](https://github.com/ewels/MultiQC/files/293944/S1_ILLUMINA.merge.dedup.realign.recal.snpeff.stats.summary.txt)
Hello Phil,
I am trying to execute multiqc on a folder with snpeff results and don't seem to have any luck getting multiqc to identify the file. 

```
I am executing multiqc . in the directory  in question

```

I get the following:

```
multiqc .
[INFO   ]         multiqc : This is MultiQC v0.7.dev0
[INFO   ]         multiqc : Searching '.'
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete

```

Here is the partial header of the file (am attaching the file below)

```


# Summary table 

Name , Value
Genome , hg19 
Date , 2016-06-01 12:56
SnpEff_version , SnpEff 3.5c (build 2014-02-21), by Pablo Cingolani
Command_line_arguments , SnpEff  hg19 -snp -s S1_ILLUMINA.merge.dedup.realign.recal.snpeff.stats S1_ILLUMINA.merge.dedup.realign.recal.vcf -csvStats 
Warnings , 116 
Number_of_lines_in_input_file, 9493
Number_of_variants_before_filter, 9510
Filter, ( ChangeType >= SNP)
Number_of_variants_filtered_out, 982
Number_of_not_variants , 0
Number_of_variants_processed , 8528
Number_of_known_variants <br>(i.e. non-empty ID) , 8021, 94.054878% 
Number_of_effects , 23359 
Genome_total_length ,3137161264 
Genome_effective_length ,3095693983 
Change_rate , 363003 

```

I am using version 3.5c of snpeff and not sure if that alone is the issue.

Thanks
Arun

**Comment by ewels** [comment] 2016-06-02 08:18
Hi Arun,

The SnpEff MultiQC module [looks for](https://github.com/ewels/MultiQC/blob/master/multiqc/utils/search_patterns.yaml#L97-L98) files matching the filename `*snpEff.summary.csv`, which is why it's not finding your file. The logs themselves look pretty similar though, so it should work with a different search pattern. See the [documentation](http://multiqc.info/docs/#module-search-patterns) for how to do this.

I'm slightly hesitant to change the default search pattern to `*.summary.{txt,csv}` as this is a lot more generic and may clash with other modules. I could search inside the file for a string, but this is slower. What's your reason for running the older version of SnpEff? (Trying to gauge how common this may be).

Phil

**Comment by ewels** [comment] 2016-06-02 08:21
Ah, follow up - I just realised that this output filename is specified with the `-stats` flag in SnpEff, so it's not standardised at all (only from within our [internal pipeline](https://github.com/johandahlberg/piper/blob/master/src/main/scala/molmed/utils/VariantCallingUtils.scala#L582)). If this is the case I'll have to search for the string inside the file anyway.

Phil

**Comment by ewels** [comment] 2016-06-02 08:33
Ok, this development version should now work for you. I tested it with your file and it seemed ok.

Let me know if you run into any problems!

**Comment by ramaniak** [comment] 2016-06-02 13:05
Thanks, Phil! I will try it out today. I work on a computational
infrastructure maintained by a core team and the only version of snpeff
available at the moment is 3.5c and hence I am using an older version of
snpeff. I will ask them to upgrade to the latest version while at it.

Thanks

Arun

Arun Ramani Ph.D.
Centre for Computational Medicine
Hospital for SickKids

**Comment by ewels** [comment] 2016-06-02 13:18
Great stuff - MultiQC should now work for you even without updating SnpEff, but yeah - never hurts to stay up to date I guess :)

**Comment by mariabernard** [comment] 2018-11-09 15:12
Dear all,

I could not find how to launch multiqc on SNPEff output

Here is my SNPEff command line:

`java -jar snpEff-4.3t/snpEff/snpEff.jar eff -csvStats snp_snpeff.csv Omyk_1.0 snp.vcf.gz > snp_snpeff.vcf.gz`

I obtain a snp_snpeff.csv file whiche look like this : 
```
# Summary table 

Name , Value
Genome , Omyk_1.0 
Date , 2018-11-09 15:04
SnpEff_version , SnpEff 4.3t (build 2017-11-24 10:18), by Pablo Cingolani
Command_line_arguments , SnpEff  Omyk_1.0 -csvStats snp.vcf.gz 
Warnings , 22026928 
Number_of_lines_in_input_file, 15064416

...

# Change rate by chromosome

Chromosome , Length , Changes , Change_rate 
ref|NC_001717.1| , 16642 , 97 , 171
ref|NC_035077.1| , 84884017 , 627172 , 135
ref|NC_035078.1| , 85480851 , 619115 , 138

...

# Variantss by type

Type , Count , Percent 
SNP , 15159306 , 100% 

# Effects by impact

Type , Count , Percent 
HIGH , 6439 , 0.01306% 
LOW , 425899 , 0.86383% 

..... etc 

```

I use multiqc (1.5) like this : 
```
multiqc -n report_snpeff_snp -m snpeff *.csv
[WARNING]         multiqc : MultiQC Version v1.6 now available!
[INFO   ]         multiqc : This is MultiQC v1.5
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching 'snp_snpeff.csv'
[INFO   ]         multiqc : Only using modules snpeff
Searching 1 files..  [####################################]  100%
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete
```

Am I doing something wrong ?

**Comment by ewels** [comment] 2018-11-12 16:30
Hi @mariabernard,

The above was fixed in the v1.6 release of MultiQC. I think if you update then it should work.

Phil

**Comment by grzadr** [comment] 2019-01-21 07:49
I am facing similar problem:

```
$multiqc -n report_snpeff_snp -m snpeff *.csv
[WARNING]         multiqc : MultiQC Version v1.7 now available!
[INFO   ]         multiqc : This is MultiQC v1.6
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching 'snpeff.summary.csv'
[INFO   ]         multiqc : Only using modules snpeff
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete
```

First lines of file looks like this:
```
# Summary table 

Name , Value
Genome , CanFam3.1.Ensembl.94 
Date , 2019-01-20 17:23
SnpEff_version , SnpEff 4.3t (build 2017-11-24 10:18), by Pablo Cingolani
Command_line_arguments , SnpEff  -csvStats /data/variants/metrics/snpeff_summary.csv CanFam3.1.Ensembl.94 /data/variants/var.raw.vcf 
Warnings , 1837561 
Number_of_lines_in_input_file, 11514988
```

**Comment by ewels** [comment] 2019-01-21 08:48
Hi @grzadr,

I just tried running MultiQC on the header of your file and it found it correctly (then crashed as it was missing later content). Could you please post the entire file and also the full MultiQC log when run with `-v`?

Thanks,

Phil

**Comment by grzadr** [comment] 2019-01-21 08:51
```
$ multiqc -v -n report_snpeff_snp -m snpeff *.csv
[2019-01-21 09:49:27,914] multiqc                                            [DEBUG  ]  No MultiQC config found: /opt/conda/lib/python3.6/site-packages/multiqc_config.yaml
[2019-01-21 09:49:27,915] multiqc                                            [DEBUG  ]  No MultiQC config found: /home/jovyan/.multiqc_config.yaml
[2019-01-21 09:49:27,916] multiqc                                            [DEBUG  ]  No MultiQC config found: multiqc_config.yaml
[2019-01-21 09:49:27,916] multiqc                                            [DEBUG  ]  Command used: /opt/conda/bin/multiqc -v -n report_snpeff_snp -m snpeff snpeff.csv snpeff_summary.csv
[2019-01-21 09:49:28,352] multiqc                                            [WARNING]  MultiQC Version v1.7 now available!
[2019-01-21 09:49:28,352] multiqc                                            [INFO   ]  This is MultiQC v1.6
[2019-01-21 09:49:28,352] multiqc                                            [DEBUG  ]  Command     : /opt/conda/bin/multiqc -v -n report_snpeff_snp -m snpeff snpeff.csv snpeff_summary.csv
[2019-01-21 09:49:28,352] multiqc                                            [DEBUG  ]  Working dir : /data/variants/metrics
[2019-01-21 09:49:28,353] multiqc                                            [INFO   ]  Template    : default
[2019-01-21 09:49:28,353] multiqc                                            [INFO   ]  Searching 'snpeff.csv'
[2019-01-21 09:49:28,353] multiqc                                            [INFO   ]  Searching 'snpeff_summary.csv'
[2019-01-21 09:49:28,354] multiqc                                            [INFO   ]  Only using modules snpeff
[2019-01-21 09:49:28,354] multiqc                                            [DEBUG  ]  Analysing modules: snpeff
[2019-01-21 09:49:28,380] multiqc                                            [DEBUG  ]  Using temporary directory for creating report: /tmp/tmp6eblmm1a
[2019-01-21 09:49:28,442] multiqc                                            [DEBUG  ]  Ignored search patterns as didn't match running modules: adapterRemoval, afterqc, bamtools/stats, bbmap/stats, bbmap/aqhist, bbmap/bhist, bbmap/bincov, bbmap/bqhist, bbmap/covhist, bbmap/covstats, bbmap/ehist, bbmap/gchist, bbmap/idhist, bbmap/ihist, bbmap/indelhist, bbmap/lhist, bbmap/mhist, bbmap/qahist, bbmap/qhist, bbmap/rpkm, bbmap/statsfile_machine, bbmap/statsfile, bcftools/stats, bcl2fastq, biobloomtools, bismark/align, bismark/dedup, bismark/meth_extract, bismark/m_bias, bismark/bam2nuc, bowtie1, bowtie2, busco, custom_content, clipandmerge, clusterflow/logs, clusterflow/runfiles, conpair/concordance, conpair/contamination, cutadapt, dedup, deeptools/bamPEFragmentSize, deeptools/estimateReadFiltering, deeptools/plotCoverageStdout, deeptools/plotCoverageOutRawCounts, deeptools/plotEnrichment, deeptools/plotFingerprintOutRawCounts, deeptools/plotFingerprintOutQualityMetrics, fastp, fastq_screen, fastqc/data, fastqc/zip, fastqc/theoretical_gc, featurecounts, flexbar, gatk/varianteval, gatk/base_recalibrator, goleft_indexcov/roc, goleft_indexcov/ped, happy, htseq, hicexplorer, hicup, hicpro/mmapstat, hicpro/mpairstat, hicpro/mergestat, hicpro/mRSstat, hicpro/assplit, hisat2, homer/findpeaks, homer/GCcontent, homer/genomeGCcontent, homer/RestrictionDistribution, homer/LengthDistribution, homer/tagInfo, homer/FreqDistribution, interop/summary, interop/index-summary, jellyfish, kallisto, kat, leehom, longranger/summary, longranger/invocation, macs2, methylQA, mirtrace/summary, mirtrace/length, mirtrace/contaminationbasic, mirtrace/mirnacomplexity, disambiguate, peddy/summary_table, peddy/het_check, peddy/ped_check, peddy/sex_check, peddy/background_pca, picard/alignment_metrics, picard/basedistributionbycycle, picard/gcbias, picard/hsmetrics, picard/insertsize, picard/markdups, picard/oxogmetrics, picard/pcr_metrics, picard/rnaseqmetrics, picard/rrbs_metrics, picard/sam_file_validation, picard/wgs_metrics, preseq, preseq/real_counts, prokka, qorts, qualimap/bamqc/genome_results, qualimap/bamqc/coverage, qualimap/bamqc/insert_size, qualimap/bamqc/genome_fraction, qualimap/bamqc/gc_dist, qualimap/rnaseq/rnaseq_results, qualimap/rnaseq/coverage, quast, rna_seqc/metrics, rna_seqc/coverage, rna_seqc/correlation, rsem, rseqc/bam_stat, rseqc/gene_body_coverage, rseqc/inner_distance, rseqc/junction_annotation, rseqc/junction_saturation, rseqc/read_gc, rseqc/read_distribution, rseqc/read_duplication_pos, rseqc/infer_experiment, salmon/meta, salmon/fld, samblaster, samtools/stats, samtools/flagstat, samtools/idxstats, samtools/rmdup, sargasso, skewer, slamdunk/summary, slamdunk/PCA, slamdunk/rates, slamdunk/utrrates, slamdunk/tcperreadpos, slamdunk/tcperutrpos, sortmerna, star, star/genecounts, supernova/report, supernova/summary, supernova/molecules, supernova/kmers, theta2, tophat, trimmomatic, vcftools/relatedness2, vcftools/tstv_by_count, vcftools/tstv_by_qual, vcftools/tstv_summary, verifybamid/selfsm
[2019-01-21 09:49:28,635] multiqc                                            [DEBUG  ]  No samples found: snpeff
[2019-01-21 09:49:28,635] multiqc                                            [WARNING]  No analysis results found. Cleaning up..
[2019-01-21 09:49:28,635] multiqc                                            [INFO   ]  MultiQC complete
```

**Comment by ewels** [comment] 2019-01-21 08:57
Can you please post the entire file as well? So that I can try to replicate the error.

**Comment by grzadr** [comment] 2019-01-21 09:00
[snpeff_summary.zip](https://github.com/ewels/MultiQC/files/2778165/snpeff_summary.zip)

**Comment by ewels** [comment] 2019-01-21 09:00
You can also try running MultiQC with the test data that I have: https://github.com/ewels/MultiQC_TestData/tree/master/data/modules/snpEff

**Comment by ewels** [comment] 2019-01-21 09:02
Confirmed, I also don't find it. I'll look into it now..

**Comment by grzadr** [comment] 2019-01-21 09:06
I can confirm that your test file works correctly.

**Closed** 2019-01-21 09:42 UTC
Labels: bug

**Comment by grzadr** [comment] 2019-01-21 10:07
Now it works like it should :)
Thanks!

Only comment I have that yaml you provided doesn't work. I had to modify it slightly:
```
sp:
  snpeff: {
    contents: 'SnpEff_version',
    max_filesize: 5000000
  }
```

**Comment by ewels** [comment] 2019-01-21 10:11
Really? That's weird - I copied and pasted from my working test. The two syntaxes should be parsed identically I think.. (http://yaml-online-parser.appspot.com/ seems to agree with my hunch). Never mind - as long as it's working! 👍
