### ISSUE TITLE
Multiqc not creating usual file with fastqc module

### ISSUE THREAD

**Issue by ChadAHighfill** [ewels/MultiQC#1674] opened 2022-05-03 16:17 UTC
I have looked through the documentation and not seeing any answers to my error. I have a snakemake rule that is static and cloned via github.  Currently v1.8 is called and has always worked until the current version 1.12 was dropped. Now `multiqc/fastqc_report_data/mqc_fastqc_overrepresented_sequencesi_plot_1.txt` isn't being created and causing my pipeline to fail. However, I am pulling in 1.8 as usual, bug in tool? This has ran fine 100s of times, and I cant figure this out.

```python
rule multiqc_fastqc:
    input: expand('fastqc/{sampleID}_trimmed_R1_fastqc.zip', sampleID=sampleIDs)
    output:
        'multiqc/fastqc_report_data/multiqc_fastqc.txt',
        'multiqc/fastqc_report_data/multiqc_general_stats.txt',
        'multiqc/fastqc_report_data/mqc_fastqc_overrepresented_sequencesi_plot_1.txt'
    run:
        shell('multiqc multiqc/cutadapt fastqc -f -p -n fastqc_report -o multiqc')
```

error:

```
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 32
Rules claiming more threads will be scaled down.
Job counts:
        count   jobs
        1       multiqc_fastqc
        1

[Tue May  3 06:13:33 2022]
rule multiqc_fastqc:
    input: fastqc/SC892124-GCCTATCA-AATGGTCG_trimmed_R1_fastqc.zip, fastqc/SC892125-CTTACCTG-GCAATGAG_trimmed_R1_fastqc.zip, fastqc/SC892127-GAGCTTGT-CCTCGA$
    output: multiqc/fastqc_report_data/multiqc_fastqc.txt, multiqc/fastqc_report_data/multiqc_general_stats.txt, multiqc/fastqc_report_data/mqc_fastqc_overr$
    jobid: 0

[WARNING]         multiqc : MultiQC Version v1.12 now available!
[INFO   ]         multiqc : This is MultiQC v1.8
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching   : PATH/CUTADAPT # edit this for this post
[INFO   ]         multiqc : Searching   : PATH/MULTIQC # edit this for this post
[INFO   ]        cutadapt : Found 28 reports
[INFO   ]          fastqc : Found 56 reports
[INFO   ]         multiqc : Compressing plot data
[WARNING]         multiqc : Deleting    : multiqc/fastqc_report.html   (-f was specified)
[WARNING]         multiqc : Deleting    : multiqc/fastqc_report_data   (-f was specified)
[INFO   ]         multiqc : Report      : multiqc/fastqc_report.html
[INFO   ]         multiqc : Data        : multiqc/fastqc_report_data
[WARNING]         multiqc : Deleting    : multiqc/multiqc_plots   (-f was specified)
[INFO   ]         multiqc : Plots       : multiqc/multiqc_plots
[INFO   ]         multiqc : MultiQC complete
Waiting at most 120 seconds for missing files.
MissingOutputException in line 190 of PATH/SNAKEFILE # edit this for this post
Job completed successfully, but some output files are missing. Missing files after 120 seconds:
multiqc/fastqc_report_data/mqc_fastqc_overrepresented_sequencesi_plot_1.txt
This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait.
```

**Comment by ewels** [comment] 2022-05-03 18:59
Hi @ChadAHighfill,

Sorry to hear that you're having problems. Have you checked your output files to see if there is another file that looks very similar to `multiqc/fastqc_report_data/mqc_fastqc_overrepresented_sequencesi_plot_1.txt`? My guess is that this is due to variance in your input data, the `_1` suffix is usually added when MultiQC runs a module twice I think. Are you sure nothing has changed in your config or input files?

I very much doubt that v1.12 being released would have any effect on how v1.8 runs, so I'm pretty sure that this is a red herring.

It looks like I did indeed fix a typo in this output filename back in v1.11: https://github.com/ewels/MultiQC/commit/d0e1fdfe27629cabc6f6995ec37688d8f00f6561 so when running 1.11 or newer you will need to update your Snakemake rule accordingly. Generally there is no guarantee that output filenames will remain constant between releases.

Phil

**Comment by ChadAHighfill** [comment] 2022-05-06 21:16
Hi Team, 

I am still having trouble. Using Version 1.11 or 1.12 when I run multiqc multiqc/cutadapt fastqc -f -p -n fastqc_report -o multiqc from the command line with python 3.7 or 3.8. I am still not getting fastqc_overrepresented_sequences_plot.txt file. Why is this? I am getting everything else but this. I just need to output this information: 'Sum of remaining over-represented sequences_R1'. Any help on generating this would be awesome.

**Comment by ewels** [comment] 2022-05-10 05:51
Please can you send me the `ls` of your `multiqc_data` folder? Also a FastQC report. I think some old versions of FastQC don't include overrepresented sequences.

**Comment by ChadAHighfill** [comment] 2022-05-10 12:56
Hi Phil,

Please see attachments you requested. As mentioned before, I was able to produce over the last year the "mqc_fastqc_overrepresented_sequencesi_plot_1.txt". I care about this column in this file: Sum of remaining over-represented sequences. When I run the last command I mentioned in python. I am not seeing this file anymore.

From: Phil Ewels ***@***.***>
Sent: Tuesday, May 10, 2022 12:52 AM
To: ewels/MultiQC ***@***.***>
Cc: Highfill, Chad (NIH/NCI) [C] ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ewels/MultiQC] Multiqc not creating usual file with fastqc module (Issue #1674)


Please can you send me the ls of your multiqc_data folder? Also a FastQC report. I think some old versions of FastQC don't include overrepresented sequences.

-
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fewels%2FMultiQC%2Fissues%2F1674%23issuecomment-1121959076&data=05%7C01%7Cchad.highfill%40nih.gov%7C5a0fc1e0677042ca807408da32492a61%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637877587070475126%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2Bbzhu3xf8Ty9bpQbtmUx10FpaMjGSHsBkfGUC87nAb8%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQPNG4IDN45CLJLC4YGQSGTVJH2O7ANCNFSM5U7MPEHA&data=05%7C01%7Cchad.highfill%40nih.gov%7C5a0fc1e0677042ca807408da32492a61%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637877587070475126%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=pmJ7125%2FWifWQqKDIPZjMvV8IIioaZX1CUu0uJIriY4%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and are confident the content is safe.

**Comment by ewels** [comment] 2022-05-10 12:58
Hi @ChadAHighfill - no attachments made it to the GitHub issue I'm afraid.

**Comment by ChadAHighfill** [comment] 2022-05-10 13:01
Hi Phil, 

Please see attachments you requested. As mentioned before, I was able to produce over the last year the “mqc_fastqc_overrepresented_sequencesi_plot_1.txt”. I care about this column in this file: Sum of remaining over-represented sequences. When I run the last command I mentioned in python. I am not seeing this file anymore. 

<img width="837" alt="mutliqc" src="https://user-images.githubusercontent.com/69129073/167634240-fbc791d2-8da2-4fd8-80f3-0ddb3c11ab37.PNG">

**Comment by ChadAHighfill** [comment] 2022-05-10 13:06
As for the fastqc_report.html. I dont know how to upload this.

**Comment by ewels** [comment] 2022-05-10 14:17
ok great, that explains it then 👍🏻 

> So I guess is there a way to force mutliqc to force this?

Not without editing the code. The file you're using is auto-generated because of the plot, so we'd have to specifically save the same output to a file separately from the plotting code. Probably as a new field in the `multiqc_fastqc` file, which is always there. There's `overrepresented_sequences` already which gives a pass / warn / fail, so could add a `overrepresented_sequences_sum` field if you fancy having a go and opening a pull request.

Otherwise, can you just tell snakemake that it's an optional output so that it doesn't crash if the file isn't there? I'm a Nextflow user myself and am quite used to this pattern, but not sure if it's a common method in Snakemake.

Phil

**Comment by ewels** [comment] 2022-05-11 05:33
Closing this issue as it's not a bug with MultiQC. If you'd like one of the suggestions above as a new feature, please contribute a pull request or open a new issue 👍🏻

**Closed** 2022-05-11 05:34 UTC

**Comment by ChadAHighfill** [comment] 2022-10-11 07:00
Hi Team,

I switch the typo, this has no effect. Very weird that the update to 1.12
has caused my pipeline to all of a sudden fail. I have no similar files
that you suggested. If you happen to think of anything else that would be
helpful, please let me know.

Best,
Chad
