### ISSUE TITLE
custom content MultiQC module broke

### ISSUE THREAD

**Issue by carmelinacharalambous** [ewels/MultiQC#1688] opened 2022-05-18 17:17 UTC
### Description of bug

Config file that worked for multiqc v1.10.1.7 partially works for multiqc v1.12 

Report is generated but some modules are missing.
I'm attaching the config file (nucleo_CH_config_v1.0.yaml changed to .txt as .yml is not supported). 

### File that triggers the error

[nucleo_CH_config_v1.0.txt](https://github.com/ewels/MultiQC/files/8718592/nucleo_CH_config_v1.0.txt)

### MultiQC Error log

```console
$  /// MultiQC 🔍 | v1.13.dev0

|           multiqc | Report title: MSK CMO MultiQC Report
|           multiqc | Search path : /wMJDfE
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 68/68  
|             table | Not able to apply table conditional formatting to '' ({'lt': 2000})
|             table | Not able to apply table conditional formatting to '' ({'eq': 2000})
|             table | Not able to apply table conditional formatting to '' ({'gt': 500})
|             table | Not able to apply table conditional formatting to '' ({'eq': 500})
|             table | Not able to apply table conditional formatting to '' ({'gt': 2000})
|             table | Not able to apply table conditional formatting to '' ({'lt': 500})
|             table | Not able to apply table conditional formatting to '' ({'lt': 100})
|             table | Not able to apply table conditional formatting to '' ({'lt': 170})
|             table | Not able to apply table conditional formatting to '' ({'eq': 170})
|             table | Not able to apply table conditional formatting to '' ({'gt': 163})
|             table | Not able to apply table conditional formatting to '' ({'eq': 163})
|             table | Not able to apply table conditional formatting to '' ({'gt': 170})
|             table | Not able to apply table conditional formatting to '' ({'lt': 163})
|             table | Not able to apply table conditional formatting to '' ({'gt': 180})
|             table | Not able to apply table conditional formatting to '' ({'lt': 150})
|             table | Not able to apply table conditional formatting to '' ({'lt': 100000000})
|             table | Not able to apply table conditional formatting to '' ({'eq': 100000000})
|             table | Not able to apply table conditional formatting to '' ({'gt': 50000000})
|             table | Not able to apply table conditional formatting to '' ({'eq': 50000000})
|             table | Not able to apply table conditional formatting to '' ({'gt': 100000000})
|             table | Not able to apply table conditional formatting to '' ({'lt': 50000000})
|             table | Not able to apply table conditional formatting to '' ({'lt': 1000000})
|             table | Not able to apply table conditional formatting to '' ({'gt': 0.97})
|             table | Not able to apply table conditional formatting to '' ({'eq': 0.97})
|             table | Not able to apply table conditional formatting to '' ({'lt': 0.97})
|             table | Not able to apply table conditional formatting to '' ({'lt': 0.95})
|    custom_content | genstats_qcstatus_plasma: Found 1 samples (table)
|    custom_content | biometrics_major_collapsed: Found 1 samples (table)
╭───────────────────────────────────────── Oops! The 'custom_content' MultiQC module broke... ─────────────────────────────────────────╮
│ Please copy this log and report it at https://github.com/ewels/MultiQC/issues                                                        │
│ Please attach a file that triggers the error. The last file found was: ./aggregate_qc_stats/qc_criteria.csv                          │
│                                                                                                                                      │
│ Traceback (most recent call last):                                                                                                   │
│   File "/usr/local/lib/python3.6/site-packages/multiqc/multiqc.py", line 651, in run                                                 │
│     output = mod()                                                                                                                   │
│   File "/usr/local/lib/python3.6/site-packages/multiqc/modules/custom_content/custom_content.py", line 277, in custom_module_classes │
│     parsed_modules[mod_id].add_cc_section(c_id, mod)                                                                                 │
│   File "/usr/local/lib/python3.6/site-packages/multiqc/modules/custom_content/custom_content.py", line 418, in add_cc_section        │
│     if section_description.strip(".") == self.info.strip("."):                                                                       │
│ AttributeError: 'NoneType' object has no attribute 'strip'                                                                           │
│                                                                                                                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
|          mosdepth | Found 1 reports
|            picard | Found 1 AlignmentSummaryMetrics reports
/usr/local/lib/python3.6/site-packages/multiqc/modules/picard/HsMetrics.py:369: RuntimeWarning: Mean of empty slice.
  vals_avg = vals[gc_binned == bin_index].mean()
/usr/local/lib/python3.6/site-packages/numpy/core/_methods.py:170: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
```

**Comment by ewels** [comment] 2022-06-20 21:20
Hi @carmelinacharalambous,

Any reason you closed this? Looks like a genuine bug with that traceback 🤔 Even if stuff is weird / wrong in the custom content file you shouldn't get unhandled tracebacks like that.

Phil

**Comment by phue** [comment] 2022-07-01 13:39
This seems to introduced this: https://github.com/ewels/MultiQC/commit/ea18493fdd2b5f34cac100ef401fcaa250ea0d9d

**Comment by ewels** [comment] 2022-07-01 13:46
Ah good spot, thanks @phue 👍🏻  Should be an easy fix.

**Comment by ewels** [comment] 2022-07-01 13:49
I'm struggling to reproduce - the log says that the last file was `./aggregate_qc_stats/qc_criteria.csv` but the attached file is a huge MultiQC config (possibly the biggest I've ever seen 😅) with no data.

**Comment by ewels** [comment] 2022-07-01 13:53
Ok, just pushed a "blind" fix - wasn't able to reproduce the error but going on what you said @phue I think this should have hopefully fixed it..

**Closed** 2022-07-01 13:52 UTC
Labels: custom-content, module: bug

**Comment by phue** [comment] 2022-07-01 13:57
:ninja: that was quick :eyes: 

I guess this would have been the alternative:
https://github.com/phue/MultiQC/commit/a38ffc66892c65b655955100b60fd2d1b6e5e9ed

**Comment by ewels** [comment] 2022-07-01 14:13
Ah sorry 😅 Yup, that works as well 👍🏻 Is actually more consistent..
