### ISSUE TITLE
'picard' MultiQC module broke

### ISSUE THREAD

**Issue by ariadnacolmeneroc** [ewels/MultiQC#1739] opened 2022-08-09 12:16 UTC
### Description of bug

I am trying to run Multiqc and I am using the TXTs resulting from HsCollectMetrics (Picard) as input. Is it OK to use this input? Why do I get the following error? 

Thank you very much, I look forward to your answer as soon as possible,

### MultiQC Error log

```console
Traceback (most recent call last):                                                                                                          │
│   File "/usr/local/lib/python3.6/dist-packages/multiqc-1.13.dev0-py3.6.egg/multiqc/multiqc.py", line 654, in run                            │
│     output = mod()                                                                                                                          │
│   File "/usr/local/lib/python3.6/dist-packages/multiqc-1.13.dev0-py3.6.egg/multiqc/modules/picard/picard.py", line 78, in __init__          │
│     n["HsMetrics"] = HsMetrics.parse_reports(self)                                                                                          │
│   File "/usr/local/lib/python3.6/dist-packages/multiqc-1.13.dev0-py3.6.egg/multiqc/modules/picard/HsMetrics.py", line 189, in parse_reports │
│     "min": 0,                                                                                                                               │
│   File "/usr/local/lib/python3.6/dist-packages/multiqc-1.13.dev0-py3.6.egg/multiqc/plots/table.py", line 53, in plot                        │
│     return make_table(dt)                                                                                                                   │
│   File "/usr/local/lib/python3.6/dist-packages/multiqc-1.13.dev0-py3.6.egg/multiqc/plots/table.py", line 157, in make_table                 │
│     val = header["modify"](val)                                                                                                             │
│   File "/usr/local/lib/python3.6/dist-packages/multiqc-1.13.dev0-py3.6.egg/multiqc/modules/picard/HsMetrics.py", line 299, in <lambda>      │
│     headers[h]["modify"] = lambda x: x * config.base_count_multiplier                                                                       │
│ TypeError: can't multiply sequence by non-int of type 'float'
```

**Comment by jasteen** [comment] 2022-08-10 06:48
i'm getting the same error just recently. is there any chance you have samples with zero reads assigned to them?  the first sample that triggers the error in my dataset is an empty sample with zero reads. (the lab people only processed half a plate but didnt tell me, so I used a sample sheet with all samples on it)

**Comment by ewels** [comment] 2022-08-16 10:58
Please could one of you attach an example file for me to replicate the error 👍🏻 

Thanks!

**Comment by ewels** [comment] 2023-01-07 14:05
Hi @ariadnacolmeneroc + @jasteen,

Reminder that I cannot fix this error without any example data. Please attach some and I'll take a look. Otherwise I will close this issue soon if I get no reply.

Thanks,

Phil

**Comment by kgowen-fl67** [comment] 2023-01-27 19:26
Hey Phil,

I've also seen this error (or similar) when processing blanks or process controls (aka water). My interpretation was that picard tools with very small bam file (aka a few reads) can sometimes technically finish but doesn't have enough reads to get a least 1 count in all the meaningful bins (on target, off target, etc). So it presumably hits some div0 errors and subs in '?' (a literal question mark) where it cant do math.

The end result breaks MultiQC which is expecting a number and is getting a pesky punctuation instead.

Here's an example file if it helps. I'd also love to see MultiQC gracefully bypass this picard edge-case. 

```
## METRICS CLASS	picard.analysis.directed.HsMetrics
BAIT_SET	BAIT_TERRITORY	BAIT_DESIGN_EFFICIENCY	ON_BAIT_BASES	NEAR_BAIT_BASES	OFF_BAIT_BASES	PCT_SELECTED_BASES	PCT_OFF_BAIT	ON_BAIT_VS_SELECTED	MEAN_BAIT_COVERAGE	PCT_USABLE_BASES_ON_BAIT	PCT_USABLE_BASES_ON_TARGET	FOLD_ENRICHMENT	HS_LIBRARY_SIZE	HS_PENALTY_10X	HS_PENALTY_20X	HS_PENALTY_30X	HS_PENALTY_40X	HS_PENALTY_50X	HS_PENALTY_100X	TARGET_TERRITORY	GENOME_SIZE	TOTAL_READS	PF_READS	PF_BASES	PF_UNIQUE_READS	PF_UQ_READS_ALIGNED	PF_BASES_ALIGNED	PF_UQ_BASES_ALIGNED	ON_TARGET_BASES	PCT_PF_READS	PCT_PF_UQ_READS	PCT_PF_UQ_READS_ALIGNED	MEAN_TARGET_COVERAGE	MEDIAN_TARGET_COVERAGE	MAX_TARGET_COVERAGE	MIN_TARGET_COVERAGE	ZERO_CVG_TARGETS_PCT	PCT_EXC_DUPE	PCT_EXC_ADAPTER	PCT_EXC_MAPQ	PCT_EXC_BASEQ	PCT_EXC_OVERLAP	PCT_EXC_OFF_TARGET	FOLD_80_BASE_PENALTY	PCT_TARGET_BASES_1X	PCT_TARGET_BASES_2X	PCT_TARGET_BASES_10X	PCT_TARGET_BASES_20X	PCT_TARGET_BASES_30X	PCT_TARGET_BASES_40X	PCT_TARGET_BASES_50X	PCT_TARGET_BASES_100X	AT_DROPOUT	GC_DROPOUT	HET_SNP_SENSITIVITY	HET_SNP_Q	SAMPLE	LIBRARY	READ_GROUP
baits	8353222	0.419316	0	0	1557	0	1	?	0	0	0	0		0	0	0	0	0	0	3502641	3095693983	24	24	2410	24	12	1557	1557	0	1	1	0.5	0	0	0	0	1	0	0	0	0.046885	0.430957	0.522158	?	0	0	0	0	0	0	0	0	0	0	0	0			
```
[Water.hs_summary.txt](https://github.com/ewels/MultiQC/files/10522436/Water.hs_summary.txt)

Thanks for everything, looking forward to seeing what you dream up at Seqera.

Best,

Kyle

**Comment by ewels** [comment] 2023-01-27 20:39
Hi @kgowen-fl67,

Many thanks for the example file! However, when I run MultiQC with it I get no error:

```
  /// MultiQC 🔍 | v1.15.dev0 (abcdcb5)

|           multiqc | Search path : /Users/ewels/GitHub/MultiQC/TestData/data/modules/picard/HsMetrics/issue_1739
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 1/1
|            picard | Found 1 HsMetrics reports
|           multiqc | Compressing plot data
|           multiqc | Report      : multiqc_report.html
|           multiqc | Data        : multiqc_data
|           multiqc | MultiQC complete
```
[multiqc_report.html.zip](https://github.com/ewels/MultiQC/files/10522966/multiqc_report.html.zip)

This suggests that the bug has already been fixed. Looking back at issues, I guess this is a duplicate of https://github.com/ewels/MultiQC/issues/1296 which was fixed in https://github.com/ewels/MultiQC/pull/1471 . However, that was released in MultiQC v1.11 and the original post here has `multiqc-1.13.dev` in the Python path. So if you guys are running a version of MultiQC newer than v1.11 I'm not sure why you're still seeing the problem.

Could you please confirm that you get this error with the latest version of MultiQC, with this file?

Thanks,

Phil

**Comment by kgowen-fl67** [comment] 2023-01-28 00:16
Hey Phil,

Apologies, It looks like I grabbed the wrong file (went looking for one with a '?') and assumed it was the breaking file. The real villain is below... it has even more punctuation. Just tested locally on the single file with v1.14 and got the following error:
```
  /// MultiQC 🔍 | v1.14

|           multiqc | Search path : /scratch/failed_multiqc/test2/Water.hs_summary.txt
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 1/1  
╭────────────────────────────────────────────────── Oops! The 'picard' MultiQC module broke... ──────────────────────────────────────────────────╮
│ Please copy this log and report it at https://github.com/ewels/MultiQC/issues                                                                  │
│ Please attach a file that triggers the error. The last file found was: Water.hs_summary.txt                                                    │
│                                                                                                                                                │
│ Traceback (most recent call last):                                                                                                             │
│   File "/opt/conda/envs/HarbingerAnalysisPipeline/lib/python3.8/site-packages/multiqc/multiqc.py", line 654, in run                            │
│     output = mod()                                                                                                                             │
│   File "/opt/conda/envs/HarbingerAnalysisPipeline/lib/python3.8/site-packages/multiqc/modules/picard/picard.py", line 77, in __init__          │
│     n["HsMetrics"] = HsMetrics.parse_reports(self)                                                                                             │
│   File "/opt/conda/envs/HarbingerAnalysisPipeline/lib/python3.8/site-packages/multiqc/modules/picard/HsMetrics.py", line 152, in parse_reports │
│     plot=table.plot(                                                                                                                           │
│   File "/opt/conda/envs/HarbingerAnalysisPipeline/lib/python3.8/site-packages/multiqc/plots/table.py", line 53, in plot                        │
│     return make_table(dt)                                                                                                                      │
│   File "/opt/conda/envs/HarbingerAnalysisPipeline/lib/python3.8/site-packages/multiqc/plots/table.py", line 157, in make_table                 │
│     val = header["modify"](val)                                                                                                                │
│   File "/opt/conda/envs/HarbingerAnalysisPipeline/lib/python3.8/site-packages/multiqc/modules/picard/HsMetrics.py", line 322, in <lambda>      │
│     headers[h]["modify"] = lambda x: x * 100.0                                                                                                 │
│ TypeError: can't multiply sequence by non-int of type 'float'                                                                                  │
│                                                                                                                                                │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
|           multiqc | No analysis results found. Cleaning up..
|           multiqc | MultiQC complete

```

This is the relevant excerpt from HS Metrics:
```
## METRICS CLASS	picard.analysis.directed.HsMetrics
BAIT_SET	BAIT_TERRITORY	BAIT_DESIGN_EFFICIENCY	ON_BAIT_BASES	NEAR_BAIT_BASES	OFF_BAIT_BASES	PCT_SELECTED_BASES	PCT_OFF_BAIT	ON_BAIT_VS_SELECTED	MEAN_BAIT_COVERAGE	PCT_USABLE_BASES_ON_BAIT	PCT_USABLE_BASES_ON_TARGET	FOLD_ENRICHMENT	HS_LIBRARY_SIZE	HS_PENALTY_10X	HS_PENALTY_20X	HS_PENALTY_30X	HS_PENALTY_40X	HS_PENALTY_50X	HS_PENALTY_100X	TARGET_TERRITORY	GENOME_SIZE	TOTAL_READS	PF_READS	PF_BASES	PF_UNIQUE_READS	PF_UQ_READS_ALIGNED	PF_BASES_ALIGNED	PF_UQ_BASES_ALIGNED	ON_TARGET_BASES	PCT_PF_READS	PCT_PF_UQ_READS	PCT_PF_UQ_READS_ALIGNED	MEAN_TARGET_COVERAGE	MEDIAN_TARGET_COVERAGE	MAX_TARGET_COVERAGE	MIN_TARGET_COVERAGE	ZERO_CVG_TARGETS_PCT	PCT_EXC_DUPE	PCT_EXC_ADAPTER	PCT_EXC_MAPQ	PCT_EXC_BASEQ	PCT_EXC_OVERLAP	PCT_EXC_OFF_TARGET	FOLD_80_BASE_PENALTY	PCT_TARGET_BASES_1X	PCT_TARGET_BASES_2X	PCT_TARGET_BASES_10X	PCT_TARGET_BASES_20X	PCT_TARGET_BASES_30X	PCT_TARGET_BASES_40X	PCT_TARGET_BASES_50X	PCT_TARGET_BASES_100X	AT_DROPOUT	GC_DROPOUT	HET_SNP_SENSITIVITY	HET_SNP_Q	SAMPLE	LIBRARY	READ_GROUP
baits	8353222	0.419316	0	0	0	?	?	?	0	0	0	?		0	0	0	0	0	0	3502641	3095693983	44	44	3836	44	0	0	0	0	1	1	0	0	0	0	0	1	?	?	?	?	?	?	?	0	0	0	0	0	0	0	0	0	0	0	0			
```

This is the file:
[Water.hs_summary.txt](https://github.com/ewels/MultiQC/files/10523976/Water.hs_summary.txt)

**Comment by ewels** [comment] 2023-01-30 20:06
Gotcha, that one did the trick - thanks! 👍🏻 

The reason that it suggested the wrong file is because the error was actually coming from core MultiQC library code, when the module tried to print the table. It was attempting to convert a fraction value by `100.0` to be a percentage (`PCT_SELECTED_BASES`), but the value was `?`.

Instead of a fix for specifically this value, I've made the core library code a bit more resilient. It now handles this type of exception and carries on, leaving the `?` as a `?` and just logging a debug warning log message.

**Comment by ewels** [comment] 2023-01-30 20:07
Thanks everyone for helping with this! Once again, being able to reproduce the error myself was essential for fixing it 🚀

**Closed by ewels** 2023-01-30 20:06 UTC
Labels: module: bug
