### ISSUE TITLE
Plots don't appear when using vcftools --TsTv-by-qual

### ISSUE THREAD

**Issue by PhilPalmer** [ewels/MultiQC#900] opened 2019-02-13 17:01 UTC
**Description of bug:**
Plots in the `multiqc_report.html` are not appearing. There is just a grey background and the text `loading...` This is for all six plots and they do not seem to be appearing despite waiting for a long time

![image](https://user-images.githubusercontent.com/32334279/52728972-2e5b5d80-2fb0-11e9-955b-b0b84adb91e6.png)

I have also seen the following [issue](https://github.com/ewels/MultiQC/issues/437) and so don't know if the cause is the same. I.e. a problem with the samtools/vcftools submodule due to an error with the plot command in python.

I had also done the same locally on my mac with a smaller BAM file and it worked fine, however, I got this error on an AWS EC2 instance with a larger BAM.

To produce the report I had run [DeepVariant](https://github.com/lifebit-ai/DeepVariant
) with the following BAM file: 
`s3://deepvariant-data/test-bam/hg19-testSmall1.1/wgEncodeUwRepliSeqBg02esG1bAlnRep1.bam` and run the following commands for samtools & vcftools to generate the data for multiqc:
```
samtools stats $bam > stats.txt
samtools flagstat $bam > flagstat.txt
samtools idxstats $bam > idxstats.txt
vcftools --vcf $vcf --TsTv-summary
vcftools --vcf $vcf --TsTv-by-count
vcftools --vcf $vcf --TsTv-by-qual
```

**MultiQC Error log:**
None MultiQC completed successfully

**File that triggers the error:**
I have uploaded the multiqc_data (including the log file) and report to the following repo: [PhilPalmer/multiqc_data](https://github.com/PhilPalmer/multiqc_data)

**MultiQC run details (please complete the following):**
 - Command used to run MultiQC: `multiqc . -m vcftools -m samtools`
 - MultiQC Version: MultiQC v1.4
 - Operating System: ?
 - Python Version: Python 2.7.14
 - Method of MultiQC installation: using docker container `maxulysse/multiqc:latest`

 **Additional context**
For full details on the pipeline, container & processes etc. that were run and to see the report go [here](https://deploit.lifebit.ai/public/jobs/5c64108dd041a800b235e3d0)

Any ideas whats causing the problem and how to fix it. 
Thanks in advance, any help would be much appreciated

**Comment by ewels** [comment] 2019-02-13 17:18
Hi @PhilPalmer,

Any reason you're using v1.4 of MultiQC? Could you try upgrading to v1.7 and seeing if you still get the same problem please?

Phil

**Comment by PhilPalmer** [comment] 2019-02-13 17:38
Hi @ewels,

Thanks for your prompt reply (as always) 😄 

The only reason I was using v1.4 was becuase that's what was installed in the container I was using. 

I will try running it with your docker container instead (`ewels/multiqc:v1.7`). When I run multiqc in the `multiqc_data` folder it only produces one of the plots so I think I need to rerun the pipeline to get the data. This will take 40mins

**Comment by PhilPalmer** [comment] 2019-02-13 18:30
@ewels,

Unfortunately I still get the same problem with v1.7

**Comment by ewels** [comment] 2019-02-13 20:28
This is super weird, as expected it's a JSON parsing error which is breaking the entire page (`Unexpected token I in JSON at position 11269`). I've not seen this one before though.

To debug this I really need to be able to replicate the run myself. Are you able to get to the nextflow work directory where MultiQC is running and get a copy of all of the input files it uses? The `multiqc_data` folder is just the parsed data from MultiQC and doesn't replicate the run. Once we have the input files you can go through running subsets until you find the specific one that is causing the error. Once we have that I can try reproducing it on my end and figure out what on earth is going on..

Phil

**Comment by PhilPalmer** [comment] 2019-02-14 09:41
@ewels, I have uploaded all of the required files from the workdir to the repo [here](https://github.com/PhilPalmer/multiqc_data/tree/master/workdir)

I am not sure if the problem is with the BAM file as lots of the values from the samtools commands are 0

**Comment by ewels** [comment] 2019-11-15 15:29
Hi @PhilPalmer,

Apologies for going quiet - I've been away on paternity leave for ages. I'm going back through MultiQC issues now and would like to address this one, but it looks like you've deleted your MultiQC_TestData fork and with it the example data..

Am I too late, or do you still have this kicking around for me to play with?

Phil

**Comment by ewels** [comment] 2019-11-15 15:34
I just tried running MultiQC with the data you pasted above and it worked fine. I'm guessing that this bug was fixed in https://github.com/ewels/MultiQC/pull/896

Closing now. If you manage to test with the latest v1.8dev code and still have problems, let me know and I can reopen it.

Phil

**Closed by ewels** 2019-11-15 15:34 UTC
Labels: bug
