### ISSUE TITLE
picard module - TypeError

### ISSUE THREAD

**Issue by massi287** [ewels/MultiQC#2038] opened 2023-09-14 03:07 UTC

**Comment by vladsavelyev** [comment] 2023-09-14 07:45
@massi287 - did you mean to provide more information about the issue? 

Note that suggested way to file an issue is to use the "Bug report" [button](https://github.com/ewels/MultiQC/issues/new/choose), which creates a form according to the bug report template.

**Comment by ewels** [comment] 2023-09-23 07:20
Likely a duplicate of https://github.com/ewels/MultiQC/issues/2063

Closing as no information in this issue.

**Closed** 2023-09-23 07:20 UTC
Labels: awaiting-response-from-user
