### ISSUE TITLE
did not show all data results in multiqc.html result, where the input file is .json (fatsp output)

### ISSUE THREAD

**Issue by prabirbioinfo** [ewels/MultiQC#2217] opened 2023-12-06 18:24 UTC
after running fastp , i used json file as input to run multiqc. i have total 3 json file consist of  read1, read2 data (like-SRR...R1, SRR..R2). multiqc showed a result, where only one result was showing.
![Screenshot (4)](https://github.com/ewels/MultiQC/assets/152770217/745ceed3-a88e-40bc-a119-ba08ddb7e575)
what would be solution? i want all json file result , as like ( SRR...R1, SRR..R2, DRR..R1, DRR..R2)

**Comment by ewels** [comment] 2023-12-13 11:05
Duplicate of https://community.seqera.io/t/fastp-not-enough-samples-showing/326/5 where this was resolved.

**Closed by ewels** 2023-12-13 11:05 UTC
Labels: waiting: example data
