### ISSUE TITLE
fastp tool

### ISSUE THREAD

**Issue by rojinsafavi** [ewels/MultiQC#784] opened 2018-06-23 21:49 UTC
* **Name of tool:**
    * [fastp]
* **Tool description:**
    * [eg. RNAseq preprocessing (new version of afterQC)]
* **Tool homepage:**
    * [https://github.com/OpenGene/fastp]

**Comment by ewels** [comment] 2018-06-24 08:41
Duplicate of #669

PR to add this module in #782

**Closed by ewels** 2018-06-24 08:41 UTC
Labels: duplicate
