### ISSUE TITLE
sambamba's bar plot value is negative

### ISSUE THREAD

**Issue by wahaha233333** [ewels/MultiQC#1951] opened 2023-07-12 11:00 UTC
### Description of bug

![image](https://github.com/ewels/MultiQC/assets/72922610/cd35ca4e-9393-42b0-bbe9-d6947fb4bab7)

```
sambamba 1.0.0
 by Artem Tarasov and Pjotr Prins (C) 2012-2022
    LDC 1.28.1 / DMD v2.098.1 / LLVM12.0.0 / bootstrap LDC - the LLVM D compiler (1.28.1)

finding positions of the duplicate reads in the file...
  sorted 1999796 end pairs
     and 9902693 single ends (among them 0 unmatched pairs)
  collecting indices of duplicate reads...   done in 6529 ms
  found 9943459 duplicates
collected list of positions in 2 min 6 sec
removing duplicates...
collected list of positions in 2 min 27 sec
```

### Before submitting

- [x] I have read the [troubleshooting documentation](https://multiqc.info/docs/#troubleshooting-1).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment] 2023-08-11 15:24
Hi @wahaha233333, I can't reproduce the problem on the test data that we have for sambamba. Could you please share the input that use passed into MultiQC?

**Comment by vladsavelyev** [comment] 2023-12-13 23:51
Closing as I don't have enough info to reproduce it :(

**Closed by vladsavelyev** 2023-12-13 23:51 UTC
Labels: bug: module, waiting: response
