### ISSUE TITLE
ZeroDivisionError in module fastp

### ISSUE THREAD

**Issue by tmshaver** [ewels/MultiQC#850] opened 2018-10-29 23:25 UTC
**Description of bug:**
Encountered a ZeroDivisionError in the fastp module when trying to process a fastq that had abnormally read counts (presumably 0 after fastp filtering). Issue is similar to https://github.com/ewels/MultiQC/issues/661; could likely just use a try/except to return NA if total_reads = 0. Happy to open a PR if you'd like.

**MultiQC Error log:**
```

============================================================
Module fastp raised an exception: Traceback (most recent call last):
  File "/home/pipestage/shared/miniconda3/bin/multiqc", line 440, in multiqc
    output = mod()
  File "/home/pipestage/shared/miniconda3/lib/python3.6/site-packages/multiqc/modules/fastp/fastp.py", line 43, in __init__
    self.parse_fastp_log(f)
  File "/home/pipestage/shared/miniconda3/lib/python3.6/site-packages/multiqc/modules/fastp/fastp.py", line 237, in parse_fastp_log
    self.fastp_insert_size_data[s_name][i+1] = (float(v) / float(total_reads)) * 100.0
ZeroDivisionError: float division by zero
============================================================

```

**File that triggers the error:**
[fastp_log.json.gz](https://github.com/ewels/MultiQC/files/2527498/fastp_log.json.gz)

**MultiQC run details (please complete the following):**
 - Command used to run MultiQC: `multi_qc {params.output_folder} -o {params.log_dir}` [in Snakemake]
 - MultiQC Version: 1.6
 - Operating System: macOS High Sierra 10.13.4
 - Python Version: 3.6.6
 - Method of MultiQC installation: pip

**Comment by ewels** [comment] 2018-11-12 16:17
Hi @tmshaver,

I suspect that this is a duplicate of https://github.com/ewels/MultiQC/issues/845, in which case it's already fixed. Please try grabbing a copy of the latest development code and see if it works (see the readme for how to do this).

Let me know if it's still broken with the dev code and I can reopen.

Phil

**Closed by ewels** 2018-11-12 16:17 UTC
