### ISSUE TITLE
TypeError when using on FastQC output zips

### ISSUE THREAD

**Issue by CelineKowalczyk** [ewels/MultiQC#410] opened 2017-02-28 21:52 UTC
I'm trying to use MultiQC to aggregate FastQC (0.11.5) reports (on Windows with Python 3). However I always get the following error.

```
$ multiqc .
[INFO   ]         multiqc : This is MultiQC v0.9
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching '.'
[INFO   ]          fastqc : Found 16 reports
[INFO   ]         multiqc : Report      : multiqc_report.html
[INFO   ]         multiqc : Data        : multiqc_data
```
```python
Traceback (most recent call last):
  File "C:/Users/lucp8769/AppData/Local/Programs/Python/Python36/Scripts/multiqc", line 579, in <module>
    multiqc()
  File "C:\users\lucp8769\appdata\local\programs\python\python36\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\users\lucp8769\appdata\local\programs\python\python36\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\users\lucp8769\appdata\local\programs\python\python36\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\users\lucp8769\appdata\local\programs\python\python36\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:/Users/lucp8769/AppData/Local/Programs/Python/Python36/Scripts/multiqc", line 507, in multiqc
    report_output = j_template.render(report=report, config=config)
  File "C:\users\lucp8769\appdata\local\programs\python\python36\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "C:\users\lucp8769\appdata\local\programs\python\python36\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\users\lucp8769\appdata\local\programs\python\python36\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\users\lucp8769\appdata\local\programs\python\python36\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\lucp8769\AppData\Local\Temp\tmp6ro4fbqf\base.html", line 19, in top-level template code
    {% include 'includes.html' %}
  File "C:\Users\lucp8769\AppData\Local\Temp\tmp6ro4fbqf\includes.html", line 33, in top-level template code
    <style type="text/css">{{ include_file(css_href, None) }}</style>
  File "C:/Users/lucp8769/AppData/Local/Programs/Python/Python36/Scripts/multiqc", line 494, in include_file
    with io.open (os.path.join(fdir, name), "r", encoding='utf-8') as f:
  File "C:\users\lucp8769\appdata\local\programs\python\python36\lib\ntpath.py", line 75, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by ewels** [comment] 2017-03-01 06:11
Hi @CelineKo,

This is a new one! How did you install MultiQC? It looks like it can't find a template file used by the FastQC module, I'm not sure why that would be..

Phil

**Comment by CelineKo** [comment] 2017-03-01 10:14
Hello Phil,

I installed MultiQC with pip. Here is the type of files I have in my analysis directory!

Céline

[Report_fastqc.zip](https://github.com/ewels/MultiQC/files/810300/Report_fastqc.zip)

**Comment by ewels** [comment] 2017-03-01 10:28
Thanks Céline - as I guessed, I have no problems running MultiQC with your data. I tried again with your version of Python and MultiQC and it still worked. I suspect that something has gone wrong during the installation.

You could try forcing pip to reinstall MultiQC:
```bash
pip install multiqc --force-reinstall --ignore-installed
```

If that doesn't help, I recommend using conda to manage your Python environment - it often solves weird difficulties such as this. You can install [miniconda](https://conda.io/miniconda.html) quite easily, then either install with `pip` (now part of your conda environment) or better still bioconda:

```bash
# first, install conda
conda create --name work python pip multiqc
source activate testing
which multiqc
# check that the path to MultiQC looks like it's from conda, not the previous
# C:/Users/lucp8769/AppData/Local/Programs/Python/Python36/Scripts/multiqc
```

Let me know if you get anywhere with that..

Phil

**Comment by CelineKowalczyk** [comment] 2017-03-02 21:22
Thank you very much for your help!

I did try with pip both on Windows and Linux (I even tried installing directly from GitHub with pip) but I always get the same error.

However, it worked perfectly with bioconda!

**Comment by ewels** [comment] 2017-03-03 08:45
Hmm, so you got the same error on two different systems? That's a bit worrying! I'm not really sure why you would get this error and it's a bit tricky to diagnose remotely - it kind of requires poking around all of your installation files to see what ended up where.

Anyway, I'm glad you got it working in the end! For now I'll close this issue and not take any action, at least until someone else encounters the same problem.

Phil

**Comment by IljaKroonen** [comment] 2017-03-03 14:12
Issue can be easily reproduced using docker.

1. Create empty folder
2. Add Report_fastqc.zip to it (file posted by Celine)
3. Add a Dockerfile with the contents below
4. Run docker build .

```
FROM python

RUN pip install multiqc

WORKDIR /reports

ADD Report_fastqc.zip Report_fastqc.zip
RUN multiqc .
```
We get the following log:
```
Step 1/5 : FROM python
 ---> 3984f3aafbc9
Step 2/5 : RUN pip install multiqc
 ---> Running in fb9f4c3c4a39
Collecting multiqc
  Downloading multiqc-0.9.tar.gz (962kB)
Collecting jinja2 (from multiqc)
  Downloading Jinja2-2.9.5-py2.py3-none-any.whl (340kB)
Collecting simplejson (from multiqc)
  Downloading simplejson-3.10.0.tar.gz (77kB)
Collecting pyyaml (from multiqc)
  Downloading PyYAML-3.12.tar.gz (253kB)
Collecting click (from multiqc)
  Downloading click-6.7-py2.py3-none-any.whl (71kB)
Collecting matplotlib (from multiqc)
  Downloading matplotlib-2.0.0-cp36-cp36m-manylinux1_x86_64.whl (14.7MB)
Collecting MarkupSafe>=0.23 (from jinja2->multiqc)
  Downloading MarkupSafe-0.23.tar.gz
Collecting python-dateutil (from matplotlib->multiqc)
  Downloading python_dateutil-2.6.0-py2.py3-none-any.whl (194kB)
Collecting numpy>=1.7.1 (from matplotlib->multiqc)
  Downloading numpy-1.12.0-cp36-cp36m-manylinux1_x86_64.whl (16.8MB)
Collecting pytz (from matplotlib->multiqc)
  Downloading pytz-2016.10-py2.py3-none-any.whl (483kB)
Collecting cycler>=0.10 (from matplotlib->multiqc)
  Downloading cycler-0.10.0-py2.py3-none-any.whl
Collecting six>=1.10 (from matplotlib->multiqc)
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting pyparsing!=2.0.0,!=2.0.4,!=2.1.2,!=2.1.6,>=1.5.6 (from matplotlib->multiqc)
  Downloading pyparsing-2.1.10-py2.py3-none-any.whl (56kB)
Installing collected packages: MarkupSafe, jinja2, simplejson, pyyaml, click, six, python-dateutil, numpy, pytz, cycler, pyparsing, matplotlib, multiqc
  Running setup.py install for MarkupSafe: started
    Running setup.py install for MarkupSafe: finished with status 'done'
  Running setup.py install for simplejson: started
    Running setup.py install for simplejson: finished with status 'done'
  Running setup.py install for pyyaml: started
    Running setup.py install for pyyaml: finished with status 'done'
  Running setup.py install for multiqc: started
    Running setup.py install for multiqc: finished with status 'done'
Successfully installed MarkupSafe-0.23 click-6.7 cycler-0.10.0 jinja2-2.9.5 matplotlib-2.0.0 multiqc-0.9 numpy-1.12.0 pyparsing-2.1.10 python-dateutil-2.6.0 pytz-2016.10 pyyaml-3.12 simplejson-3.10.0 si
x-1.10.0
 ---> 44fce74872e4
Removing intermediate container fb9f4c3c4a39
Step 3/5 : WORKDIR /reports
 ---> 98572c067184
Removing intermediate container 1838ecbe8927
Step 4/5 : ADD Report_fastqc.zip Report_fastqc.zip
 ---> 023fb6e6cfbf
Removing intermediate container 451c3727d036
Step 5/5 : RUN multiqc .
 ---> Running in a5459e6453f2
[INFO   ]         multiqc : This is MultiQC v0.9
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching '.'
[INFO   ]          fastqc : Found 1 reports
[INFO   ]         multiqc : Report      : multiqc_report.html
[INFO   ]         multiqc : Data        : multiqc_data
Traceback (most recent call last):
  File "/usr/local/bin/multiqc", line 579, in <module>
    multiqc()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/bin/multiqc", line 507, in multiqc
    report_output = j_template.render(report=report, config=config)
  File "/usr/local/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/tmp/tmpo_nmyn33/base.html", line 19, in top-level template code
    {% include 'includes.html' %}
  File "/tmp/tmpo_nmyn33/includes.html", line 33, in top-level template code
    <style type="text/css">{{ include_file(css_href, None) }}</style>
  File "/usr/local/bin/multiqc", line 494, in include_file
    with io.open (os.path.join(fdir, name), "r", encoding='utf-8') as f:
  File "/usr/local/lib/python3.6/posixpath.py", line 78, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
The command '/bin/sh -c multiqc .' returned a non-zero code: 1
```

**Comment by ewels** [comment] 2017-03-08 11:57
Hi @IljaKroonen,

Thank you for your instructions - I followed them and am now able to replicate the behaviour as well. I have no idea what's going on here, I'll look into it..

Phil

**Comment by ewels** [comment] 2017-03-08 12:24
Ok, I think I've tracked it down. The offending code was trying to use `os.path.join` with a variable that was `None`. Apparently this works on my system and on Travis / everywhere else that I've previously tested, but not in the above docker installation. So I guess that it's some kind of system-specific thing?

Anyway - thankfully it was an easy fix, just replacing `None` with `''`. Everything seems to work now:

**Dockerfile**
```
FROM python

RUN pip install --upgrade --force-reinstall git+https://github.com/ewels/MultiQC.git

WORKDIR /reports

ADD Report_fastqc.zip Report_fastqc.zip
RUN multiqc .
```

**Log**
```
Sending build context to Docker daemon 418.3 kB
Step 1/5 : FROM python
 ---> a1782fa44ef7
Step 2/5 : RUN pip install --upgrade --force-reinstall git+https://github.com/ewels/MultiQC.git
 ---> Running in b29c7c37bafd
Collecting git+https://github.com/ewels/MultiQC.git
  Cloning https://github.com/ewels/MultiQC.git to /tmp/pip-w2bpn9bj-build
Collecting jinja2 (from multiqc==1.0.dev0)
  Downloading Jinja2-2.9.5-py2.py3-none-any.whl (340kB)
Collecting simplejson (from multiqc==1.0.dev0)
  Downloading simplejson-3.10.0.tar.gz (77kB)
Collecting pyyaml (from multiqc==1.0.dev0)
  Downloading PyYAML-3.12.tar.gz (253kB)
Collecting click (from multiqc==1.0.dev0)
  Downloading click-6.7-py2.py3-none-any.whl (71kB)
Collecting matplotlib (from multiqc==1.0.dev0)
  Downloading matplotlib-2.0.0-cp36-cp36m-manylinux1_x86_64.whl (14.7MB)
Collecting MarkupSafe>=0.23 (from jinja2->multiqc==1.0.dev0)
  Downloading MarkupSafe-1.0.tar.gz
Collecting pyparsing!=2.0.0,!=2.0.4,!=2.1.2,!=2.1.6,>=1.5.6 (from matplotlib->multiqc==1.0.dev0)
  Downloading pyparsing-2.2.0-py2.py3-none-any.whl (56kB)
Collecting python-dateutil (from matplotlib->multiqc==1.0.dev0)
  Downloading python_dateutil-2.6.0-py2.py3-none-any.whl (194kB)
Collecting cycler>=0.10 (from matplotlib->multiqc==1.0.dev0)
  Downloading cycler-0.10.0-py2.py3-none-any.whl
Collecting numpy>=1.7.1 (from matplotlib->multiqc==1.0.dev0)
  Downloading numpy-1.12.0-cp36-cp36m-manylinux1_x86_64.whl (16.8MB)
Collecting six>=1.10 (from matplotlib->multiqc==1.0.dev0)
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting pytz (from matplotlib->multiqc==1.0.dev0)
  Downloading pytz-2016.10-py2.py3-none-any.whl (483kB)
Installing collected packages: MarkupSafe, jinja2, simplejson, pyyaml, click, pyparsing, six, python-dateutil, cycler, numpy, pytz, matplotlib, multiqc
  Running setup.py install for MarkupSafe: started
    Running setup.py install for MarkupSafe: finished with status 'done'
  Running setup.py install for simplejson: started
    Running setup.py install for simplejson: finished with status 'done'
  Running setup.py install for pyyaml: started
    Running setup.py install for pyyaml: finished with status 'done'
  Running setup.py install for multiqc: started
    Running setup.py install for multiqc: finished with status 'done'
Successfully installed MarkupSafe-1.0 click-6.7 cycler-0.10.0 jinja2-2.9.5 matplotlib-2.0.0 multiqc-1.0.dev0 numpy-1.12.0 pyparsing-2.2.0 python-dateutil-2.6.0 pytz-2016.10 pyyaml-3.12 simplejson-3.10.0 six-1.10.0
 ---> 18626cd83ef4
Removing intermediate container b29c7c37bafd
Step 3/5 : WORKDIR /reports
 ---> cb146de78af6
Removing intermediate container 76f6f26a4361
Step 4/5 : ADD Report_fastqc.zip Report_fastqc.zip
 ---> 39e175ccfa16
Removing intermediate container 3b4d8f32f9e9
Step 5/5 : RUN multiqc .
 ---> Running in fd093b87d45f
[INFO   ]         multiqc : This is MultiQC v1.0.dev0
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching '.'
[INFO   ]          fastqc : Found 1 reports
[INFO   ]         multiqc : Report      : multiqc_report.html
[INFO   ]         multiqc : Data        : multiqc_data
[INFO   ]         multiqc : MultiQC complete
 ---> 9523ebf1c3c9
Removing intermediate container fd093b87d45f
Successfully built 9523ebf1c3c9
```

Many thanks both!

Phil

**Closed by ewels** 2017-03-08 12:24 UTC
Labels: bug

**Comment by stephenturner** [comment] 2017-04-12 13:54
I get the same error @CelineKowalczyk originally reported. 

I had multiqc working fine on a miniconda2 installation. Switched to miniconda3, installed with pip, and got the local/ASCII/UTF-8 errors. After setting the LANG and LC_ALL env variables, I no longer had that error, but I got the NoneType error @CelineKowalczyk reported. 

I removed the pip installation and installed with conda (leaving the LANG env vars set) and had no problem.

**Comment by ewels** [comment] 2017-04-12 13:59
Hi @stephenturner,

Are you running the development version with your pip install? This bugfix hasn't made it to a release yet (one is long overdue but I've been swamped with other projects recently).

I'm not totally sure what you mean about local/ASCII/UTF-8 errors. The error reported by @CelineKowalczyk was about a system specific `None` type handling as I understand it. Am I missing something?

Phil

**Comment by stephenturner** [comment] 2017-04-12 14:49
no, just whatever pip installed.

Originally received the errors described at http://multiqc.info/docs/#locale-error-messages but after setting locale properly in my .bashrc, that's when I get @CelineKowalczyk's same errors (with pip version). Conda OK.

**Comment by ewels** [comment] 2017-04-18 13:27
Ah ok - then yes, this should resolve itself when I release the new version on PyPI in the coming days (though interesting that someone else saw the same error). Annoying about the locale errors too! Sorry that you had to mess around with that..

**Comment by ewels** [comment] 2017-04-18 13:28
Hah, so much for that then 😉  :

![twitter](https://cloud.githubusercontent.com/assets/465550/25132953/89597630-244b-11e7-9ab9-c034d28ddfcf.png)
