### ISSUE TITLE
BBMap output files not recognized

### ISSUE THREAD

**Issue by boulund** [ewels/MultiQC#621] opened 2017-11-07 09:55 UTC
Original issue by @aschuerch in my personal fork: https://github.com/boulund/MultiQC_bbmap/issues/1

> Apologies if I am not posting in the right repo but this refers to the bbmap module pull request. I run multiqc version 1.3 as a bioconda package but I seem unable to make multiqc recognize my bbmap output files, neither with or without the -tag bbmap. Is there a naming convention for bbmap output files to be recognized by multiqc?

I created this issue here for @aschuerch, who didn't know exactly where to ask about this. I figured it's better for everyone to keep the discussion in the official MultiQC repo, I hope that's fine with you @ewels. 

MultiQC identifies output files from BBMap by their contents, because unfortunately there aren't any universal naming conventions for BBMap output files at this time. As long as the files are in plaintext (i.e. not gzipped), MultiQC should detect them. Unless MultiQC has changed the file formats since we commited the BBMap module for MultiQC, it should find them. 

What version of BBMap are you using?
Could you perhaps upload an output file of yours here so we could take a look at it @aschuerch?

**Comment by aschuerch** [comment] 2017-11-07 11:01
I use BBMap version 37.62, I attached a test file (basecov)
[Test.basecov.txt] (https://github.com/ewels/MultiQC/files/1449663/Test.basecov.txt)
Which BBMap version did you use for writing the MultiQC module?

**Comment by boulund** [comment] 2017-11-07 11:05
Ah, that explains it! We haven't implemented support for the `basecov`
filetype (yet). It's quite difficult to find a good visualization of the
basecov output, especially when you have multiple samples to visualize at
once. Do you have any good ideas for how to visually represent the data in
a way that suits multiqc? If you do, let's talk further about implementing
it!

Den 7 nov. 2017 12:01 skrev "Anita Schürch" <notifications@github.com>:

**Comment by ewels** [comment] 2017-11-07 16:03
Thanks @boulund - PR merged.  I will close this issue now as the problem is essentially resolved. Ping me if you want it reopened / refocussed towards discussion of how this could be implemented.

**Closed by ewels** 2017-11-07 16:03 UTC
