### ISSUE TITLE
PCT_PF_UQ_READS_ALIGNED incorrectly reported for picard's HsMetrics

### ISSUE THREAD

**Issue by anoronh4** [ewels/MultiQC#1391] opened 2021-03-09 21:50 UTC
**Description of bug:**

column corresponding to PCT_PF_UQ_READS_ALIGNED column in multiqc report is showing all `0.0` values even though i can see in my inputs that they are between 99 and 100. interestingly, the header of the column actually says `M Pct pf uq reads aligned`, which suggests it's being interpreted in the millions. together with rounding, this might be why the numbers show up as 0. My report shows `PCT_PF_UQ_READS_ALIGNED` because i have added the following to my config:

```yaml
picard_config:
    HsMetrics_table_cols:
        ...
        - PCT_PF_UQ_READS_ALIGNED
        ...
```
I believe the presentation of the values is being decided based on the presence of `PCT` and `READS`, but since there are both in this field name, the settings for the latter are overwriting the former: 

https://github.com/ewels/MultiQC/blob/477fe3d82e008439f84081d3fa7b42ef61f059f9/multiqc/modules/picard/HsMetrics.py#L275-L284

Here's a screen shot of what i see
![Screen Shot 2021-03-09 at 4 47 24 PM](https://user-images.githubusercontent.com/9613506/110542705-6681eb80-80f7-11eb-9aca-2a703367f6c8.png)

**MultiQC Error log:**

No error is thrown

**File that triggers the error:**

any picard hsmetrics file

**MultiQC run details (please complete the following):**

- Command used to run MultiQC: multiqc .
- MultiQC Version: 1.9
- Operating System: CentOS Linux 7
- Python Version: 3.8
- Method of MultiQC installation: manual installation with `setup.py` inside of a docker image

**Comment by ewels** [comment] 2021-03-11 11:58
Duplicate of issue https://github.com/ewels/MultiQC/issues/1212

Fixed in https://github.com/ewels/MultiQC/commit/a5168f8f490986204053fc1c524d49fddd733dfc#diff-ad77258589887331db1a95a5cc3f9af5221d35dea71fbcaa4749ecf9d19ad97a and part of the v1.10 release a couple of days ago.

So if you run the latest version of MultiQC it should work fine for you 👍🏻  

Phil

**Closed by ewels** 2021-03-11 11:58 UTC
Labels: module: bug
