### ISSUE TITLE
Multiple runs of module overwrite general stats

### ISSUE THREAD

**Issue by epruesse** [ewels/MultiQC#672] opened 2018-01-25 18:44 UTC
When using multiple instances of the FastQC module, the last instance is the only one listed in General Stats.

Considering the "before/after" type workflow `raw->trimmed->mapped` with e.g. FastQC, having the number of reads left for each stage in the General Stats (and the rest in per-section general stats) would be neat.

**Comment by ewels** [comment] 2018-01-25 23:21
Yes, agreed. However, needs some thought as to how. The reason it only shows one at the moment is because of duplicate column identifiers. It would be easy to add a random suffix to prevent this, but then the user-configs that are targeted to these columns wouldn't apply.

Should be fine if we just adjust the ID if it's already present I think (eg. `#fastqc-gc`, `#fastqc-gc-2`).

**Comment by ewels** [comment] 2018-05-20 16:11
Dup of #715 (or rather, that was a duplicate of this issue). Now fixed - let me know if you still have trouble!

Phil

**Closed by ewels** 2018-05-20 16:11 UTC
Labels: core: back end
