### ISSUE TITLE
Picard metrics by Parabricks not parsed

### ISSUE THREAD

**Issue by JAMKuttan** [ewels/MultiQC#1768] opened 2022-09-20 17:48 UTC
### Description of bug

I have some text files containing Picard outputs (along with some other things). I set the search patterns and content in my config, but cannot get multiqc to recognize any of the modules. 

### File that triggers the error

```yaml
title: "Parabricks Report"
subtitle: "MultiQC Analysis"
intro_text: "An Aggregation of results and quality metrics from the genomics analysis pipelines"

extra_fn_clean_exts:
  - ".mdup.txt"
  - ".alignment.txt"
  - ".base_distribution_by_cycle.pdf"
  - ".base_distribution_by_cycle.png"
  - ".base_distribution_by_cycle.txt"
  - ".coverage_metrics.txt"
  - ".gcbias.pdf"
  - ".gcbias_0.png"
  - ".gcbias_detail.txt"
  - ".gcbias_summary.txt"
  - ".insert_size.pdf"
  - ".insert_size.png"
  - ".insert_size.txt"
  - ".mean_quality_by_cycle.pdf"
  - ".mean_quality_by_cycle.png"
  - ".mean_quality_by_cycle.txt"
  - ".quality_yield.txt"
  - ".qualityscore.pdf"
  - ".qualityscore.png"
  - ".qualityscore.txt"

custom_data:
  base_distribution_by_cycle:
    section_name: "Base Distribution By Cycle"
  insert_size:
    section_name: "Insert Size"
  quality_score:
    section_name: "Quality Score"
  gc_bias:
    section_name: "GC Bias"
  mean_quality_by_cycle:
    section_name: "Mean Quality By Cycle"

sp:
  base_distribution_by_cycle:
    fn: "*.base_distribution_by_cycle.png"
  insert_size:
    fn: "*.insert_size.png"
  quality_score:
    fn: "*.qualityscore.png"
  gc_bias:
    fn: "*.gcbias_0.png"
  mean_quality_by_cycle:
    fn: "*.mean_quality_by_cycle.png"
  picard/alignment_metrics:
    fn: "*.alignment.txt"
    contents: "picard.analysis.AlignmentSummaryMetrics"
    shared: true
  picard/basedistributionbycycle:
    fn: "*.base_distribution_by_cycle.txt"
    contents: "picard.analysis.BaseDistributionByCycleMetrics"
    shared: true
  picard/gcbias:
    fn: "*.gcbias_summary.txt"
    fn: "*.gcbias_detail.txt"
    contents: "picard.analysis.GcBias*Metrics"
    shared: true
  picard/insertsize:
    fn: "*.insert_size.txt"
    contents: "picard.analysis.InsertSizeMetrics"
    shared: true
  picard/markdups:
    fn: "*.mdup.txt"
    contents: "picard.sam.DuplicationMetrics"
    shared: true
  picard/quality_yield_metrics:
    fn: "*.quality_yield.txt"
    contents: "picard.analysis.CollectQualityYieldMetrics$QualityYieldMetrics"
    shared: true
  picard/wgs_metrics:
    fn: "*.coverage_metrics.txt"
    contents: "picard.analysis.CollectWgsMetrics$WgsMetrics"
    shared: true

ignore_images: false

top_modules:
  - 'generalstats'
```

### MultiQC Error log

```console
$ multiqc -c parabricks_config.yaml .

  /// MultiQC 🔍 | v1.13

|            config | Config 'custom_logo' path not found, skipping (bantha_logo.png)
|           multiqc | Report title: Parabricks Report
|           multiqc | Search path : /data
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 54/54
|    custom_content | base_distribution_by_cycle: Found 1 sample (image)
|    custom_content | insert_size: Found 1 sample (image)
|    custom_content | quality_score: Found 1 sample (image)
|    custom_content | gc_bias: Found 1 sample (image)
|    custom_content | mean_quality_by_cycle: Found 1 sample (image)
|            picard | Found 2 MarkDuplicates reports
|           multiqc | Compressing plot data
|           multiqc | Report      : multiqc_report.html
|           multiqc | Data        : multiqc_data
|           multiqc | MultiQC complete
```

**Comment by ewels** [comment] 2022-09-20 21:56
Hi @JAMKuttan,

It's difficult to know what's wrong here without some example files - if possible, please supply a minimum reproducible example that I can run myself (upload some files that don't work).

Is there a reason that you need to customise the Picard search patterns? Usually the defaults work fine..

Phil

**Comment by JAMKuttan** [comment] 2022-09-21 15:10
@ewels I am attaching a tar file with one sample example in it. 
[GIAB_NA12878_qcmetrics.tar.gz](https://github.com/ewels/MultiQC/files/9617951/GIAB_NA12878_qcmetrics.tar.gz)
[SRR15663418_T1_qcmetrics.tar.gz](https://github.com/ewels/MultiQC/files/9617954/SRR15663418_T1_qcmetrics.tar.gz)

**Comment by JAMKuttan** [comment] 2022-09-21 15:13
I use this script to update file names

#!/bin/bash
#multiqc.sh

for f in *_qcmetrics.tar.gz
do
    dirn="${f%.tar.gz}"
    fname="${f%_qcmetrics.tar.gz}"
    tar -xzf ${f}
    cd $dirn
    for i in *
    do
        if [[ "$i" == *.mdup.txt ]];
            then
                continue;
        fi
        mv {,$fname.}$i
    done
    cd ../
done

multiqc -c parabricks_config.yaml .

**Comment by gouinK** [comment] 2022-10-11 06:47
I am having the same issue as the OP, specifically regarding CollectWgsMetrics. I am using Parabricks as well, which is what I am guessing the OP was using. I have tried using the default search patterns (MultiQC v1.11) to no avail, even though the "CollectWgsMetrics" string is indeed in the files.

**Comment by JAMKuttan** [comment] 2022-10-13 16:42
Can confirm. I am using parabricks as well.

**Comment by LauraEgolf** [comment] 2022-10-31 20:27
Same issue here with Parabricks output (tested MultiQC v1.12 and v1.13). Using default search patterns, the CollectWgsMetrics file isn't recognized even though it includes the string.

**Comment by ewels** [comment] 2023-01-08 23:08
Yeah, I've had similar problems before with other variations of Picard tools. The log files aren't particularly easy to parse and rely on matching various strings. However, Picard output can vary a _lot_. It's a fine line to balance specificity with flexibility.

The code that needs tweaking is probably somewhere around here:

https://github.com/ewels/MultiQC/blob/e3ba446073418f158522b54ba77c306afa691d08/multiqc/modules/picard/HsMetrics.py#L71

I guess Parabricks has some variation on these strings which is why the parsing fails.

**Comment by ewels** [comment] 2023-02-08 14:35
Just had a quick look at the files. I think that the problem is because these files are missing the usual Picard header. It normally looks something like this:

```
## htsjdk.samtools.metrics.StringHeader
# picard.analysis.CollectWgsMetrics INPUT=/gpfs/projects/bioinfo/najeeb/withKhalid/PMC/PMC01/PMC01-01_AB082422_S5_L005_R1_001.bam OUTPUT=/gpfs/projects/bioinfo/najeeb/withKhalid/PMC/QC_PMC/CollectWgsMetrics/PMC01-01_AB082422_S5_L005_R1_001.txt REFERENCE_SEQUENCE=/gpfs/ngsdata/ref_data/Homo_sapiens/hs37d5/Sequences/BWAIndex/hs37d5.fa    MINIMUM_MAPPING_QUALITY=20 MINIMUM_BASE_QUALITY=20 COVERAGE_CAP=250 LOCUS_ACCUMULATION_CAP=100000 STOP_AFTER=-1 INCLUDE_BQ_HISTOGRAM=false COUNT_UNPAIRED=false SAMPLE_SIZE=10000 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json
## htsjdk.samtools.metrics.StringHeader
# Started on: Sun Jan 29 10:39:28 AST 2017

## METRICS CLASS	picard.analysis.CollectWgsMetrics$WgsMetrics
```

But your files start right away like this:

```
## METRICS CLASS	picard.analysis.CollectWgsMetrics$WgsMetrics
```

This is a problem, as we use the `INPUT` to collect the input filename to use as the sample name. Without this, the code simply ignores the rest of the file and doesn't parse any data.

The fix will be to default to using the sample name from the log filename and overwrite it if we can. This isn't ideal, as some pipelines print these stdout metrics to a single file for many samples, also in your case it gives the fairly unhelpful name `coverage_metrics` which will be the same for all samples. But it's better than ignoring the file completely.

The code will also need a bit of a refactor / rewrite, as I think it's probably too brittle with the format currently, but can be improved.

Fairly large job, as this probably needs to be done across all Picard submodules, which is quite a lot of code (though it'll be repetitive).

**Comment by vladsavelyev** [comment] 2023-12-14 00:21
> The code will also need a bit of a refactor / rewrite, as I think it's probably too brittle with the format currently, but can be improved.

> Fairly large job, as this probably needs to be done across all Picard submodules, which is quite a lot of code (though it'll be repetitive).

The large job is merged here: https://github.com/ewels/MultiQC/pull/2110 :-)

**Closed by vladsavelyev** 2023-12-14 00:21 UTC
Labels: module: change, bug: module
