### ISSUE TITLE
multiqc and hicexplorer

### ISSUE THREAD

**Issue by mcornwell1957** [ewels/MultiQC#1061] opened 2019-11-20 02:02 UTC
Hello - your tool is fantastic and I am a huge fan of it and how easy it is to use! Please find below an error with MultiQC and hicexplorer

**MultiQC Error log:**

```
/gpfs/data/ruggleslab/home/mgc439/miniconda3/envs/hiC/lib/python3.6/site-packages/multiqc/utils/config.py:45: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  configs = yaml.load(f)
/gpfs/data/ruggleslab/home/mgc439/miniconda3/envs/hiC/lib/python3.6/site-packages/multiqc/utils/config.py:51: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  sp = yaml.load(f)
[INFO   ]         multiqc : This is MultiQC v1.7
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching 'output/test1/hic/'
[ERROR  ]         multiqc : Oops! The 'hicexplorer' MultiQC module broke... 
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
  If possible, please include a log file that triggers the error - the last file found was:
    output/test1/hic/SRR927087/hicQC/QC_table.txt
============================================================
Module hicexplorer raised an exception: Traceback (most recent call last):
  File "/gpfs/data/ruggleslab/home/mgc439/miniconda3/envs/hiC/bin/multiqc", line 440, in multiqc
    output = mod()
  File "/gpfs/data/ruggleslab/home/mgc439/miniconda3/envs/hiC/lib/python3.6/site-packages/multiqc/modules/hicexplorer/hicexplorer.py", line 42, in __init__
    self.mod_data[data_]['Pairs mappable, unique and high quality'] = self.mod_data[data_]['Pairs considered']
KeyError: 'Pairs considered'
============================================================
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete
```

**File that triggers the error:**
[QC_table.txt](https://github.com/ewels/MultiQC/files/3866936/QC_table.txt)

**MultiQC run details (please complete the following):**
 - Command used to run MultiQC: [`multiqc .`]
 - MultiQC Version: [MultiQC v1.7]
 - Operating System: [Linux 3.10.0]
 - Python Version: [python 3.6.7]
 - Method of MultiQC installation: [conda]

 **Additional context**
Pretty straight forward. I use MultiQC at the end of an NGS pipeline to summarize results - works for fastqc, STAR, etc.. but not for this one module. Thanks for your help!

**Comment by ewels** [comment] 2019-11-20 10:46
Duplicate of https://github.com/ewels/MultiQC/issues/893, already fixed in https://github.com/ewels/MultiQC/pull/902 

Available in MultiQC v1.8dev, should be released imminently... 🤞 

Phil

**Closed by ewels** 2019-11-20 10:46 UTC
