### ISSUE TITLE
multiqc_config.yaml parsing could be more lenient and remove html / special characters if required.

### ISSUE THREAD

**Issue by AMChalkie** [ewels/MultiQC#713] opened 2018-03-23 06:45 UTC
**Description of bug:**
`multiqc_config.yaml` test file isn't used. File has custom / user defined tags I would like to have in the MultiQC report.
[multiqc_config2.yaml.gz](https://github.com/ewels/MultiQC/files/1840429/multiqc_config2.yaml.gz)

**MultiQC Error log:**
```
[2018-03-23 17:39:30,835] multiqc   [DEBUG  ]  New config 'report_header_info': [{'Contact E-mail (bioinformatics)': 'user@svi.edu.au'}, {'Contact E-mail (project)': 'cwalkley@svi.edu.au'}, {'Application Type': 'RNA-seq'}, {'Project Type': 'Application'}, {'Sequencing Platform': 'HiSeq PE150'}, {'Sequencing Setup': '2x150'}, {'Sequencing company': 'Novogene'}, {'Library Prep': 'Kapa kit (Performed at SVI - Scott and Jane)'}, {'Library Prep date': 'unknown'}, {'Sequencing release date': '22 march 2018'}, {'Sequencing Qc release date': '18 march 2018'}, {'Sequencing cost': '1690 USD'}, {'Library prep cost': 'unknown'}, {'Cell type': 'GMCSF derived from sample mutation/+ and +/+. Sorted cells (details required)'}, {'Date bioinformatic QC': '23 march 2018'}, {'Date bioinformatic differential expression': 'NA'}, {'Date bioinformatic alternative splicing': 'NA'}, {'Date bioinformatic SNP calling': 'NA'}, {'Requested analysis': 'QC, Salmon transcript quantification, Differential Expression, Alternative splicing, SNP calling'}]
[2018-03-23 17:39:30,836] multiqc   [ERROR  ]  Could not parse command line config: multiqc_config.yaml
```

* **Command used to run MultiQC**
    * `multiqc .`
* **MultiQC Version:**
```
[2018-03-23 17:45:28,952] multiqc   [DEBUG  ]  Latest MultiQC version is v1.5
```

**Comment by ewels** [comment] 2018-03-23 17:06
Hi @AMChalkie,

I'm a little unsure of what the problem is here. When I run MultiQC with your config file it seems to work fine:

![image](https://user-images.githubusercontent.com/465550/37843114-507678fc-2ec4-11e8-8253-1438d8758dec.png)

Note that I use the command `multiqc . -c multiqc_config2.yaml` and I don't get any error message.

The MultiQC version debug line you pasted is just telling you that the latest MultiQC release is v1.5, that particular line isn't reporting the version that you are running. You want the line after that one:

```
[2018-03-23 18:00:31,359] multiqc    [DEBUG  ]  Latest MultiQC version is v1.5
[2018-03-23 18:00:31,359] multiqc    [INFO   ]  This is MultiQC v1.5
```

Could you attach the full `multiqc_data/multiqc.log` file please?

Phil

**Comment by ewels** [comment] 2018-04-17 15:16
Hi @AMChalkie,

Let me know if you have any feedback on this issue, otherwise I'll close it in a couple of days as I'm not sure what needs doing.

Thanks,

Phil

**Comment by ewels** [comment] 2018-05-20 13:39
Closing as need more feedback to reproduce.

**Closed by ewels** 2018-05-20 13:39 UTC
