### ISSUE TITLE
MultiQC seems to crash after completion in my script file

### ISSUE THREAD

**Issue by akaviaLab** [ewels/MultiQC#1156] opened 2020-04-13 16:30 UTC
**Description of bug:**
I'm running MultiQC in a script. When MultiQC has finished, it prints out lots of error messages, and the entire script fails. However, MultiQC seems to have run successfully.

I'm running MultiQC in my script with the following commands:

```python
multiqcOutPutName = sampleName + "_multiqc_report.html"
multiqcOutDir = htmldir or outdir
multiqc.run(analysis_dir=reportFiles[sampleName], outdir=multiqcOutDir, filename=multiqcOutPutName)
```

The file `mutliqcOutDir/multiqcOutPutName` is created.

The reason I'm asking is that I'm planning to run this script as an AWS Batch pipeline, and my understanding is that if one stage fails, the entire pipeline will stop. Therefore, I can't just ignore this error, even if MultiQC has done everything required, since the pipeline has multiple other steps after MultiQC.

Thank you!

**MultiQC Error log:**
```
INFO   ]         multiqc : This is MultiQC v1.8
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching   : /home/ubuntu/CCLE/out/SRR9729388.sra.fastp.json
[INFO   ]         multiqc : Searching   : /home/ubuntu/CCLE/out/SRR9729388_fastqc.html
[INFO   ]           fastp : Found 1 reports
[INFO   ]         multiqc : Compressing plot data
[WARNING]          megaqc : Couldn't export data key 'config.analysis_dir'
[INFO   ]         multiqc : Report      : HTML/SRR9729388_multiqc_report.html
[INFO   ]         multiqc : Data        : HTML/SRR9729388_multiqc_report_data
[INFO   ]         multiqc : MultiQC complete
```

```python
Traceback (most recent call last):
  File "/usr/local/bin/run_rnacocktail.py", line 4, in <module>
    __import__('pkg_resources').run_script('RNACocktail-Pipeline==0.3.1', 'run_rnacocktail.py')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1469, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.7/dist-packages/RNACocktail_Pipeline-0.3.1-py3.7.egg/EGG-INFO/scripts/run_rnacocktail.py", line 996, in <module>
  File "/usr/local/lib/python3.7/dist-packages/RNACocktail_Pipeline-0.3.1-py3.7.egg/src/main.py", line 120, in run_pipeline
  File "/usr/local/lib/python3.7/dist-packages/RNACocktail_Pipeline-0.3.1-py3.7.egg/src/run_mergeqc.py", line 483, in run_qcLanes_mergeLanes_qcSummary
  File "/usr/local/lib/python3.7/dist-packages/multiqc-1.8-py3.7.egg/multiqc/multiqc.py", line 303, in run
    config.mqc_load_userconfig(config_file)
  File "/usr/local/lib/python3.7/dist-packages/multiqc-1.8-py3.7.egg/multiqc/utils/config.py", line 99, in mqc_load_userconfig
    mqc_load_config(os.path.join( os.path.dirname(MULTIQC_DIR), 'multiqc_config.yaml'))
  File "/usr/local/lib/python3.7/dist-packages/multiqc-1.8-py3.7.egg/multiqc/utils/config.py", line 130, in mqc_load_config
    logger.debug("No MultiQC config found: {}".format(yaml_config))
  File "/usr/lib/python3.7/logging/__init__.py", line 1366, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/usr/lib/python3.7/logging/__init__.py", line 1514, in _log
    self.handle(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 1524, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 1586, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 894, in handle
    self.emit(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 1126, in emit
    self.stream = self._open()
  File "/usr/lib/python3.7/logging/__init__.py", line 1116, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpp2l2irhw/multiqc.log'
```

**File that triggers the error:**
Please drag and drop (and upload to the GitHub issue) an input file that I can use to replicate the error.

**MultiQC run details (please complete the following):**
 - Command used to run MultiQC: See above, using it in python3 script
 - MultiQC Version: 1.8
 - Operating System: AWS ubuntu 19.10 #17-Ubuntu SMP Fri Mar 27 18:29:29 UTC 2020
 - Python Version: 3.7.5
 - Method of MultiQC installation: `pip3` (I think, it has been a while)

**Comment by ewels** [comment] 2020-04-14 08:05
Looks like a duplicate of https://github.com/ewels/MultiQC/issues/1141

This will be fixed in the next release, but for now a short-term fix is to just call MultiQC as a regular external process with [`subprocess.check_output`](https://docs.python.org/3.8/library/subprocess.html#subprocess.check_output).

Phil

**Closed by ewels** 2020-04-14 08:05 UTC
