### ISSUE TITLE
Non zero exit code on div by zero error on file generated by samtools idxstats without any reads

### ISSUE THREAD

**Issue by mmterpstra** [ewels/MultiQC#680] opened 2018-02-08 12:19 UTC
**Description of bug:**
Non zero exit code on div by zero error on file generated by `samtools idxstats` without any reads.

A mininal reproduction does not reproduce the error... you will need a second `samtools idxstats` report with reads to make the prog to throw errors.

Is this still an issue on the new releases? according to [the afflicted line](https://github.com/ewels/MultiQC/blob/master/multiqc/modules/samtools/idxstats.py#L101) it still looks like it.

**MultiQC Error log:**
```
#original
multiqc --force ./
[INFO   ]         multiqc : This is MultiQC v1.0
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching './'
[INFO   ]          snpeff : Found 28 reports
[WARNING]        bargraph : Tried to make bar plot, but had no data
[INFO   ]          picard : Found 13 BaseDistributionByCycleMetrics reports
[INFO   ]          picard : Found 13 GcBiasMetrics reports
[INFO   ]          picard : Found 14 HsMetrics reports
[INFO   ]          picard : Found 14 AlignmentSummaryMetrics reports
[INFO   ]        samtools : Found 28 stats reports
[INFO   ]        samtools : Found 14 flagstat reports
[ERROR  ]         multiqc : Oops! The 'samtools' MultiQC module broke... 
                    Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
                    (if possible, include a log file that triggers the error) 
============================================================
Module samtools raised an exception: Traceback (most recent call last):
  File "/apps/software/multiqc/1.0-foss-2015b-Python-2.7.11/lib/python2.7/site-packages/multiqc-1.0-py2.7.egg/EGG-INFO/scripts/multiqc", line 373, in multiqc
    output = mod()
  File "/apps/software/multiqc/1.0-foss-2015b-Python-2.7.11/lib/python2.7/site-packages/multiqc-1.0-py2.7.egg/multiqc/modules/samtools/samtools.py", line 50, in __init__
    n['idxstats'] = self.parse_samtools_idxstats()
  File "/apps/software/multiqc/1.0-foss-2015b-Python-2.7.11/lib/python2.7/site-packages/multiqc-1.0-py2.7.egg/multiqc/modules/samtools/idxstats.py", line 101, in parse_samtools_idxstats
    pdata_norm[s_name][k] = float(self.samtools_idxstats[s_name][k]) / sample_mapped[s_name]
ZeroDivisionError: float division by zero
============================================================
[WARNING]          fastqc : Couldn't read 'some_fastqc.zip' - Bad zip file
[INFO   ]          fastqc : Found 27 reports
[INFO   ]         multiqc : Compressing plot data
[INFO   ]         multiqc : Report      : multiqc_report.html
[INFO   ]         multiqc : Data        : multiqc_data
[INFO   ]         multiqc : MultiQC complete
```
minimal error when using my reproduction
```
[INFO   ]         multiqc : This is MultiQC v1.0
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching './'
Searching 3 files..  [####################################]  100%
[ERROR  ]         multiqc : Oops! The 'samtools' MultiQC module broke... 
                    Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
                    (if possible, include a log file that triggers the error) 
============================================================
Module samtools raised an exception: Traceback (most recent call last):
  File "/apps/software/multiqc/1.0-foss-2015b-Python-2.7.11/lib/python2.7/site-packages/multiqc-1.0-py2.7.egg/EGG-INFO/scripts/multiqc", line 373, in multiqc
    output = mod()
  File "/apps/software/multiqc/1.0-foss-2015b-Python-2.7.11/lib/python2.7/site-packages/multiqc-1.0-py2.7.egg/multiqc/modules/samtools/samtools.py", line 50, in __init__
    n['idxstats'] = self.parse_samtools_idxstats()
  File "/apps/software/multiqc/1.0-foss-2015b-Python-2.7.11/lib/python2.7/site-packages/multiqc-1.0-py2.7.egg/multiqc/modules/samtools/idxstats.py", line 101, in parse_samtools_idxstats
    pdata_norm[s_name][k] = float(self.samtools_idxstats[s_name][k]) / sample_mapped[s_name]
ZeroDivisionError: float division by zero
============================================================
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete
```

* **File that triggers the error:**
save like `sample.idxstats.log` and save a second one with the third column (one based index) set to none zero and generate a second one like `cat sample.idxstats.log| |perl -wpe 's/\t0\t0\n/\t2\t0\n/g' > sample2.idxstats.log` 

```
1	249250621	0	0
2	243199373	0	0
3	198022430	0	0
4	191154276	0	0
5	180915260	0	0
6	171115067	0	0
7	159138663	0	0
8	146364022	0	0
9	141213431	0	0
10	135534747	0	0
11	135006516	0	0
12	133851895	0	0
13	115169878	0	0
14	107349540	0	0
15	102531392	0	0
16	90354753	0	0
17	81195210	0	0
18	78077248	0	0
19	59128983	0	0
20	63025520	0	0
21	48129895	0	0
22	51304566	0	0
X	155270560	0	0
Y	59373566	0	0
MT	16569	0	0
GL000207.1	4262	0	0
GL000226.1	15008	0	0
GL000229.1	19913	0	0
GL000231.1	27386	0	0
GL000210.1	27682	0	0
GL000239.1	33824	0	0
GL000235.1	34474	0	0
GL000201.1	36148	0	0
GL000247.1	36422	0	0
GL000245.1	36651	0	0
GL000197.1	37175	0	0
GL000203.1	37498	0	0
GL000246.1	38154	0	0
GL000249.1	38502	0	0
GL000196.1	38914	0	0
GL000248.1	39786	0	0
GL000244.1	39929	0	0
GL000238.1	39939	0	0
GL000202.1	40103	0	0
GL000234.1	40531	0	0
GL000232.1	40652	0	0
GL000206.1	41001	0	0
GL000240.1	41933	0	0
GL000236.1	41934	0	0
GL000241.1	42152	0	0
GL000243.1	43341	0	0
GL000242.1	43523	0	0
GL000230.1	43691	0	0
GL000237.1	45867	0	0
GL000233.1	45941	0	0
GL000204.1	81310	0	0
GL000198.1	90085	0	0
GL000208.1	92689	0	0
GL000191.1	106433	0	0
GL000227.1	128374	0	0
GL000228.1	129120	0	0
GL000214.1	137718	0	0
GL000221.1	155397	0	0
GL000209.1	159169	0	0
GL000218.1	161147	0	0
GL000220.1	161802	0	0
GL000213.1	164239	0	0
GL000211.1	166566	0	0
GL000199.1	169874	0	0
GL000217.1	172149	0	0
GL000216.1	172294	0	0
GL000215.1	172545	0	0
GL000205.1	174588	0	0
GL000219.1	179198	0	0
GL000224.1	179693	0	0
GL000223.1	180455	0	0
GL000195.1	182896	0	0
GL000212.1	186858	0	0
GL000222.1	186861	0	0
GL000200.1	187035	0	0
GL000193.1	189789	0	0
GL000194.1	191469	0	0
GL000225.1	211173	0	0
GL000192.1	547496	0	0
NC_007605	171823	0	0
hs37d5	35477943	0	0
*	0	0	0
```
* **Command used to run MultiQC**
    * `multiqc --force ./`
* **MultiQC Version:**
    * [MultiQC v1.0]
* **Operating System:**
    * [CentOS release 6.9 (Final)]
* **Python Version:**
    * [Python-2.7.11]
* **Method of MultiQC installation:**
    * [EasyBuild (FTW) ]

**Comment by hassanfa** [comment] 2018-04-23 13:43
We tried the output you've pasted, but we can't replicate the error. We propose adding ```ZeroDivisionError``` to the try-except block, but at this point without being able to replicate the error it is pointless. Can you please send the samtools idxstats's output file itself?

**Comment by ewels** [comment] 2018-05-20 13:49
Closing as unable to reproduce. @mmterpstra - if you think that this is still an issue, please attach the raw file that triggers this error and we'll try again.

Phil

**Closed by ewels** 2018-05-20 13:49 UTC
Labels: bug

**Comment by mmterpstra** [comment] 2018-06-06 10:41
Sorry for the late reply here is the test that replicates the error. Apparently you will need two or more files with a file containing no reads and a file containing reads.

**Comment by ewels** [comment] 2018-06-06 11:37
Thanks @mmterpstra - is it possible to attach such a log file to this issue? Just trying to generate an accurate file for testing takes significantly longer than actually fixing the problem usually (and often misses the problem). If you could drag and drop the file you have which triggers the error onto the thread then we can replicate it ourselves.

**Comment by mmterpstra** [comment] 2018-06-06 13:47
Here the files are present:
https://github.com/mmterpstra/MultiQC/tree/mmterpstra-patch-samtools-idxdivby0/test/data

I suggest to move these to the test repo or just use this branch to play around with it and then only keep the relevant changes. I modified travis to include the failing files in the tests so travis automatically fails on this branch. See for example https://travis-ci.org/mmterpstra/MultiQC/jobs/388202844 to see it fail. Probably it is just an update to [the afflicted line](https://github.com/ewels/MultiQC/blob/master/multiqc/modules/samtools/idxstats.py#L101) to avoid the div by zero errors.

**Comment by ewels** [comment] 2018-06-06 14:10
Ok - test data added to the test repo and bug fixed. Thanks! Was easy once I could see the traceback..

**Comment by mmterpstra** [comment] 2018-06-06 14:13
Thanks
