### ISSUE TITLE
Missing samples in bar plots

### ISSUE THREAD

**Issue by schorlton** [ewels/MultiQC#861] opened 2018-11-18 20:54 UTC
**Description of bug:**
When running QUAST or BUSCO on my assembly, I am missing samples in the bar graphs. For example, the attached QUAST result is missing `Batch1.Cdip2` and `Batch1.Cdip3` and others in the last plot of `Number of Contigs`, but they show up in the first two tables. Running with `-s` and/or `-d` does not resolve.

**File that triggers the error:**
[report.txt](https://github.com/ewels/MultiQC/files/2593220/report.txt)
This is the QUAST output `.tsv` file. Note: I have renamed the file to `.txt` from `.tsv` to enable upload to Github.

**MultiQC run details (please complete the following):**
```
python quast.py Assemblies/*/contigs.fa -r reference.fa -L -b 
multiqc *.tsv
```
multiqc v1.6
QUAST 5.0.1

**Comment by ewels** [comment] 2018-12-21 13:38
Hi @schorlton,

I'm unable to reproduce this error I'm afraid - the samples you mention do seem to be present for me:

![image](https://user-images.githubusercontent.com/465550/50345020-c64b4680-052d-11e9-8406-0528ef23b2cd.png)

Note that to get this screenshot, I increased the vertical height of the plot. By default, the plot looks like this:
![image](https://user-images.githubusercontent.com/465550/50345033-d4996280-052d-11e9-835f-f7cb36fa80de.png)


The samples are there, it's just that the labels on the y axis are skipped so that they can be read.

To see how to resize plots, please see the [documentation](https://multiqc.info/docs/#interactive-plots).

I'll close this issue now on the assumption that I've guessed the problem correctly. Please let me know how you get on though, and if it is something else then shout and I can reopen it.

Cheers,

Phil

**Closed by ewels** 2018-12-21 13:38 UTC
Labels: bug
