### ISSUE TITLE
YAMLLoadWarning: How to fix or should I not bother

### ISSUE THREAD

**Issue by sanyalab** [ewels/MultiQC#969] opened 2019-05-10 14:06 UTC
**Description of bug:**
I am getting a YAMLLoadWarning every time I run Multiqc. Do I need to bother about this?

**MultiQC Error log:**
```

lxjh276:.../ASR-Karen/AE356$ multiqc .
/mnt/common/rh6/annotate/Python-2.7.15/lib/python2.7/site-packages/multiqc/utils/config.py:45: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  configs = yaml.load(f)
/mnt/common/rh6/annotate/Python-2.7.15/lib/python2.7/site-packages/multiqc/utils/config.py:51: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  sp = yaml.load(f)
[INFO   ]         multiqc : This is MultiQC v1.7
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching '.'
[INFO   ]          fastqc : Found 24 reports
[INFO   ]         multiqc : Compressing plot data
[INFO   ]         multiqc : Report      : multiqc_report.html
[INFO   ]         multiqc : Data        : multiqc_data
[INFO   ]         multiqc : MultiQC complete

```

**MultiQC run details (please complete the following):**
 - Command used to run MultiQC: `multiqc .`
 - MultiQC Version: MultiQC v1.7
 - Operating System: Linux RedHat 6
 - Python Version: Python 2.7.15
 - Method of MultiQC installation: `pip install multiqc`

**Comment by s-andrews** [comment] 2019-06-07 14:45
I got this too.

You can fix it by changing lines 45 and 51 in ```config.py``` so that the yaml load statements go from:

```
configs = yaml.load(f)
sp = yaml.load(f)
```

to...

```
configs = yaml.load(f, Loader=yaml.SafeLoader)
sp = yaml.load(f, Loader=yaml.SafeLoader)
```

**Comment by ewels** [comment] 2019-06-07 14:54
Sorry, I somehow missed this issue. The problem is already fixed in the v1.8dev of MultiQC and will go out when that is released. I'm away on leave at the moment which is why this hasn't happened yet sorry.

If it's annoying then you can always run the dev version of MultiQC :)

```
pip install --upgrade --force-reinstall git+https://github.com/ewels/MultiQC.git
```

**Comment by ewels** [comment] 2019-06-07 14:55
ps. You need not bother. The warning is harmless and nothing more than annoying. Installing an earlier version of the PyYAML package also removes the warning. The latest update included it because it's possible to execute arbitrary Python code using the default parser. However, unless you are accepting MultiQC config files from potential hackers, I don't think that you have anything to worry about 😁

**Comment by s-andrews** [comment] 2019-06-07 14:58
But my OCD against warning messages will keep tingling then :-)

**Comment by ewels** [comment] 2019-06-07 14:59
Dup of https://github.com/ewels/MultiQC/issues/964 and fixed in 85e92dc1cff8d7682780f4b079113b8350950d0f

**Closed by ewels** 2019-06-07 14:59 UTC

**Comment by ewels** [comment] 2019-06-07 15:00
> But my OCD against warning messages will keep tingling then :-)

I sympathise! However, my OCD of having 19 open pull requests and an overdue release is probably worse 😅

**Comment by danutasastre** [comment] 2020-04-24 19:50
Hello! From a complete newbie:

I keep getting the same warming message, even after updating MutiQC.
Can you spot what I could do to fix the issue?

Thanks a lot,
Danuta

My steps:
pip install --upgrade --force-reinstall git+https://github.com/ewels/MultiQC.git
...
ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
danutasastre@danutas-mbp Lam % multiqc .                                                                       
/Users/danutasastre/anaconda3/lib/python3.7/site-packages/multiqc/utils/config.py:45: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  configs = yaml.load(f)
/Users/danutasastre/anaconda3/lib/python3.7/site-packages/multiqc/utils/config.py:51: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  sp = yaml.load(f)
/Users/danutasastre/anaconda3/bin/multiqc:229: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  logger.warn('MultiQC Version {} now available!'.format(remote_version))
[WARNING]         multiqc : MultiQC Version v1.8 now available!
[INFO   ]         multiqc : This is MultiQC v1.7
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching '.'
/Users/danutasastre/anaconda3/bin/multiqc:495: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  logger.warn("No analysis results found. Cleaning up..")
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete
danutasastre@danutas-mbp Lam % ls
SRR8568019_1_fastqc.html	SRR8568021_1_fastqc.html	SRR8568025_1_fastqc.html
SRR8568019_2_fastqc.html	SRR8568022_2_fastqc.html	SRR8568025_2_fastqc.html
SRR8568020_1_fastqc.html	SRR8568024_1_fastqc.html	SRR8568026_1_fastqc.html
SRR8568020_2_fastqc.html	SRR8568024_2_fastqc.html	SRR8568026_2_fastqc.html

**Comment by ewels** [comment] 2020-04-27 09:17
Hi @danutasastre!

First tip is to please open a new issue for things like this, as it's tricky for me to keep track of comments on old closed issues.

But here I think the problem is that you haven't updated MultiQC, even though you tried. See the following line from your log:

```
ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

Then when you run MultiQC it tells you `This is MultiQC v1.7`. This is why you're still getting the warning message.

Installation problems like this are usually due to strange conflicts in how packages were installed by different people / different environments etc. I'd recommend trying to manually uninstall or update specifically the `PyYAML` package first, and then MultiQC. If in doubt, start with a fresh conda environment (see the [docs](https://multiqc.info/docs/#installing-with-conda)).

I hope that helps! If you're still struggling, please open a new issue.

Phil
