### ISSUE TITLE
CollectWgsMetrics Metrics with MultiQC

### ISSUE THREAD

**Issue by snashraf** [ewels/MultiQC#393] opened 2017-01-30 14:45 UTC
Thanks for a wonderful tools. You don't know how much this tool is being helping me now days.
Any chance of extending support for CollectWgsMetrics as well. This is a much used metric for WGS data.

Collect metrics about coverage and performance of whole genome sequencing (WGS) experiments.
This tool collects metrics about the fractions of reads that pass base- and mapping-quality filters as well as coverage (read-depth) levels for WGS analyses. Both minimum base- and mapping-quality values as well as the maximum read depths (coverage cap) are user defined.

Note: Metrics labeled as percentages are actually expressed as fractions!

Thanks
Najeeb
[PMC01-01_AB082422_S5_L005_R1_001.txt](https://github.com/ewels/MultiQC/files/739227/PMC01-01_AB082422_S5_L005_R1_001.txt)

Thanks!

**Comment by snashraf** [comment] 2017-02-06 14:59
Hello Hammarn,

Did you get a chance to work on this ? 

Thanks
Najeeb

**Comment by Hammarn** [comment] 2017-02-06 15:13
Hi @snashraf!
No, sorry I haven't had any time to work on this, and I probably won't have any time soon - sorry. You will have to wait for Phil to get back to you on this (he will be back at work in roughly two weeks).  And even then it might take quite a while if he decides that it's a module that is worth writing.
This is an OpenSource project and pull requests are always welcome if that something that you might be interested in. If you haven't already have a look at the documentation: 
http://multiqc.info/docs/#writing-new-modules
Chers, 
Rickard

**Comment by ewels** [comment] 2017-02-22 17:05
Duplicate of comment in #12. Added in dba14d4283b20a318da0fecc4744670148f04f6e

**Closed by ewels** 2017-02-22 17:05 UTC
Labels: module: new
