### ISSUE TITLE
TSV Tables overwriting different rows with same sample name

### ISSUE THREAD

**Issue by NewtontheNeuron** [ewels/MultiQC#1476] opened 2021-06-30 21:32 UTC
### Description of bug

Hello Multiqc team,

I am trying to add tsv files as a tables with the custom_content module. Adding the file works well, but the table does not appear the way I expect. I have attached an example of the tsv file bellow.

```
Sample	Readset	Mark Name	Raw Single Reads #	Surviving Single Reads #	Surviving Single Reads %
GM12878_chr19	GM12878_chr19_input	Input	134583	133554	99.2354
GM12878_chr19	GM12878_chr19_CTCF	CTCF	313700	301403	96.08
GM12878_chr19	GM12878_chr19_Rad21	Rad21	465712	457817	98.3047
```

In the report, only the last row is shown. However, the information in each row is different.
![image](https://user-images.githubusercontent.com/86746257/124031627-8cdcd700-d9c5-11eb-952e-a8ef60595d48.png)

I want the full tsv to be shown. The issue happens with other tsv files as well. Is there something that I overlooked? I noticed that when I change the names of the samples to `GM12878_chr19_1`, `GM12878_chr19_2`, and `GM12878_chr19_3` then all the rows are shown. But changing the name of the sample is not very ideal. It seems that the first column is used as a key for the information in the rest of the row. Is there a way to change the column that is used as a key to the second column? Can I set the key column myself? Is there a way to add a key column at the beginning and then hide the that column? Otherwise, is it on the user to prepare the data?

I look forward to your response.
Thank you.

### Command used to run MultiQC

multiqc . -o report/report_html --filename Final_report -f -c report/my_config.yaml -t my_custom_template

### MultiQC Version

v1.10.1

### Operating System

CentOS

### Python Version

3.8.10

### Method of MultiQC installation

pip

**Comment by ewels** [comment] 2021-06-30 22:24
Hi @NewtontheNeuron,

This is not something specific to your code or to custom content, this is a general thing for MultiQC - as you suspected, the sample identifier is used as a key and should not be duplicated.

See https://multiqc.info/docs/#not-enough-samples-found and https://multiqc.info/docs/#clashing-sample-names

There's no easy way to get around this here without editing your input files I'm afraid. If you put the 2nd column first (or delete the 1st column) then they will be used as identifiers and they are not duplicates.

If this output file comes from a released bioinformatics tool then another option is to write a MultiQC module for it, instead of using custom content.

There is currently no way to configure MultiQC to tell it to use a different column as the sample key. This could be something to look into, though I'm curious as to your motivation first. I'm thinking that if it's a standard output from a tool that you can't change then it should probably be a module. If it's custom output that you're generating then hopefully you can change the format.

Let me know what you think!

Phil

**Comment by ewels** [comment] 2021-06-30 22:44
Closing this issue for now as the reason for the unexpected behaviour is clear. We can open a new issue for the proposed additional custom-config config option if needed.

**Closed by ewels** 2021-06-30 22:44 UTC
Labels: custom-content
