### ISSUE TITLE
DRAGEN: parsing fails without prefilter metrics

### ISSUE THREAD

**Issue by stephenturner** [ewels/MultiQC#1244] opened 2020-07-06 19:29 UTC
First, _thank you_ 🙇 for creating the DRAGEN module in the last release. This is an excellent addition, and will help with QA/QC'ing multiple WGS runs.

**Description of bug:**

MultiQC fails to parse DRAGEN's vc_metrics.csv file when PREFILTER metrics are not included. I'm not sure when DRAGEN's behavior changed, but when running DRAGEN outputting a gVCF, only a post-filter gVCF and metrics are produced (example file shown below). The [code to parse this file](https://github.com/ewels/MultiQC/blob/8b57f47c7ada2fcdab2ea88c80f17ed904e66572/multiqc/modules/dragen/vc_metrics.py#L111-L247) looks for both PREFILTER and POSTFILTER, and throws an error when it doesn't find the expected PREFILTER values.

**MultiQC Error log:**

```
[INFO   ]         multiqc : This is MultiQC v1.9
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching   : /wgs/DRAGEN-output/NA12878_downsample
Searching 40 files..  [####################################]  100%
[ERROR  ]         multiqc : Oops! The 'dragen' MultiQC module broke...
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues
  If possible, please include a log file that triggers the error - the last file found was:
    NA12878_downsample/NA12878_downsample.vc_metrics.csv
============================================================
Module dragen raised an exception: Traceback (most recent call last):
  File "/home/sdt5z/miniconda3/envs/multiqc/lib/python3.8/site-packages/multiqc/multiqc.py", line 569, in run
    output = mod()
  File "/home/sdt5z/miniconda3/envs/multiqc/lib/python3.8/site-packages/multiqc/modules/dragen/dragen.py", line 41, in __init__
    samples_found |= self.add_vc_metrics()
  File "/home/sdt5z/miniconda3/envs/multiqc/lib/python3.8/site-packages/multiqc/modules/dragen/vc_metrics.py", line 23, in add_vc_metrics
    data = parse_vc_metrics_file(f)
  File "/home/sdt5z/miniconda3/envs/multiqc/lib/python3.8/site-packages/multiqc/modules/dragen/vc_metrics.py", line 204, in parse_vc_metrics_file
    data['Insertions'] = data['Insertions (Hom)'] + data['Insertions (Het)']
KeyError: 'Insertions (Hom)'
============================================================
```

**File that triggers the error:**

 
This is the `vc_metrics.csv` file (GitHub doesn't allow CSV uploads).

```
VARIANT CALLER SUMMARY,,Number of samples,1
VARIANT CALLER SUMMARY,,Reads Processed,88696714
VARIANT CALLER SUMMARY,,Child Sample,NA
VARIANT CALLER POSTFILTER,NA12878_downsample,Total,3149954,100.00
VARIANT CALLER POSTFILTER,NA12878_downsample,Biallelic,3040988,96.54
VARIANT CALLER POSTFILTER,NA12878_downsample,Multiallelic,108966,3.46
VARIANT CALLER POSTFILTER,NA12878_downsample,SNPs,2685496,85.26
VARIANT CALLER POSTFILTER,NA12878_downsample,Insertions (Hom),123505,3.92
VARIANT CALLER POSTFILTER,NA12878_downsample,Insertions (Het),91343,2.90
VARIANT CALLER POSTFILTER,NA12878_downsample,Deletions (Hom),125053,3.97
VARIANT CALLER POSTFILTER,NA12878_downsample,Deletions (Het),117371,3.73
VARIANT CALLER POSTFILTER,NA12878_downsample,Indels (Het),7175,0.23
VARIANT CALLER POSTFILTER,NA12878_downsample,Chr X number of SNPs over genome,81062
VARIANT CALLER POSTFILTER,NA12878_downsample,Chr Y number of SNPs over genome,0
VARIANT CALLER POSTFILTER,NA12878_downsample,(Chr X SNPs)/(chr Y SNPs) ratio over genome,NA
VARIANT CALLER POSTFILTER,NA12878_downsample,SNP Transitions,2794293
VARIANT CALLER POSTFILTER,NA12878_downsample,SNP Transversions,1363775
VARIANT CALLER POSTFILTER,NA12878_downsample,Ti/Tv ratio,2.05
VARIANT CALLER POSTFILTER,NA12878_downsample,Heterozygous,1428971
VARIANT CALLER POSTFILTER,NA12878_downsample,Homozygous,1720983
VARIANT CALLER POSTFILTER,NA12878_downsample,Het/Hom ratio,0.83
VARIANT CALLER POSTFILTER,NA12878_downsample,In dbSNP,0,0.00
VARIANT CALLER POSTFILTER,NA12878_downsample,Not in dbSNP,0,0.00
VARIANT CALLER POSTFILTER,NA12878_downsample,TMB,NA
VARIANT CALLER POSTFILTER,NA12878_downsample,TMB Denominator (MB),NA
VARIANT CALLER POSTFILTER,NA12878_downsample,Percent Callability,73.1769
VARIANT CALLER POSTFILTER,NA12878_downsample,Percent Autosome Callability,73.8562
```

**MultiQC run details (please complete the following):**

* Command used to run MultiQC: `multiqc .`
* MultiQC Version: 1.9
* Operating System: CentOS 7
* Python Version: 3.8.3
* Method of MultiQC installation: conda (and pip)

**Additional context**

DRAGEN 3.6.3 released last month. I think this issue occurred prior to the 3.6.3 release but I can't be sure. In any case, the 3.6.3 release also now outputs FASTQC metrics, at least in a CSV file. Future issue, but it might be nice to be able to pick this up and report as well.

https://support.illumina.com/content/dam/illumina-support/documents/downloads/software/dragen/DRAGEN-3.6-Customer-Release-Notes-1000000128662-00.pdf

**Comment by ohofmann** [comment] 2020-07-07 00:15
Thanks Stephen! FastQC is [already being worked on](https://github.com/ewels/MultiQC/pull/1232) but might take a bit.

**Comment by ewels** [comment] 2020-07-07 08:44
Thanks for reporting @stephenturner! I think that this looks like a duplicate of #1223, in which case it's already been fixed in `v1.10dev` by @vladsaveliev in #1224. However, we never managed to get any test data in #1223 to test the fix.

Saving your example above to `Sample_1.vc_metrics.csv` seems to work for me, at least it generates a report which looks sensible:

```console
$ multiqc .
[INFO   ]         multiqc : This is MultiQC v1.10.dev0 (96d0a2f)
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching   : /Users/philewels/GitHub/MultiQC_TestData/data/modules/dragen/issue_1244
[INFO   ]          dragen : Found 1 reports
[INFO   ]         multiqc : Compressing plot data
[INFO   ]         multiqc : Report      : multiqc_report.html
[INFO   ]         multiqc : Data        : multiqc_data
[INFO   ]         multiqc : MultiQC complete
```

Generates: [multiqc_report.html](https://github.com/ewels/MultiQC/files/4883686/multiqc_report.html.zip)


I'll close for now, but let me know if you have any trouble with the development version of MultiQC and I can reopen.

**Closed** 2020-07-07 08:44 UTC

**Comment by stephenturner** [comment] 2020-07-07 12:22
Thanks! Apologies for missing the previous issue, I must have searched open issues only. 1.10dev0 fixed the issue!

**Comment by ewels** [comment] 2020-07-07 13:04
No problem - thanks for checking! And thanks for the detailed report + example data 👍
