### ISSUE TITLE
Oops! The 'picard' MultiQC module broke...

### ISSUE THREAD

**Issue by PierreJust** [ewels/MultiQC#2061] opened 2023-09-21 16:57 UTC
### Description of bug

Oops! The 'picard' MultiQC module broke

### File that triggers the error

[example.zip](https://github.com/ewels/MultiQC/files/12689193/example.zip)

### MultiQC Error log

```console
/// MultiQC 🔍 | v1.13.dev0
  
  |           multiqc | MultiQC Version v1.15 now available!
  |           multiqc | Only using modules: adapterRemoval, bowtie2, custom_content, damageprofiler, dedup, fastp, fastqc, gatk, kraken, malt, mtnucratio, multivcfanalyzer, picard, preseq, qualimap, samtools, sexdeterrmine, hops, bcftools
  |           multiqc | Search path : multiqc_config.yaml
  |           multiqc | Search path : /mnt/archgen/users/pierre_justeau/eager_outputs/SG/GRG_Y/GRG035_test_merged_singleHeader/work/49/7a156a74b65f5d92cc721f2fc6df85
  |         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 135/135  
  |          samtools | Found 1 flagstat reports
  |          samtools | Found 1 flagstat reports
  ╭───────────────── Oops! The 'picard' MultiQC module broke... ─────────────────╮
  │ Please copy this log and report it at                                        │
  │ https://github.com/ewels/MultiQC/issues                                      │
  │ Please attach a file that triggers the error. The last file found was:       │
  │ ./markdup/GRG035_rmdup.metrics                                               │
  │                                                                              │
  │ Traceback (most recent call last):                                           │
  │   File "/opt/conda/envs/nf-core-eager-2.4.5/lib/python3.9/site-packages/mult │
  │     parsed_data[k] += float(vals[i])                                         │
  │ ValueError: could not convert string to float: 'double'                      │
  │                                                                              │
  │ During handling of the above exception, another exception occurred:          │
  │                                                                              │
  │ Traceback (most recent call last):                                           │
  │   File "/opt/conda/envs/nf-core-eager-2.4.5/lib/python3.9/site-packages/mult │
  │     output = mod()                                                           │
  │   File "/opt/conda/envs/nf-core-eager-2.4.5/lib/python3.9/site-packages/mult │
  │     n["MarkDuplicates"] = MarkDuplicates.parse_reports(self)                 │
  │   File "/opt/conda/envs/nf-core-eager-2.4.5/lib/python3.9/site-packages/mult │
  │     parsed_data[k] += " / " + vals[i]                                        │
  │ TypeError: unsupported operand type(s) for +=: 'float' and 'str'             │
  │                                                                              │
  ╰──────────────────────────────────────────────────────────────────────────────╯
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/#troubleshooting-1).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by ewels** [comment] 2023-09-23 07:45
Thanks for reporting! Closing as I think that this is a duplicate of https://github.com/ewels/MultiQC/issues/2063

**Closed** 2023-09-23 07:45 UTC
Labels: module: bug

**Comment by ewels** [comment] 2023-10-03 09:52
@PierreJust - should now be fixed in the development version of MultiQC. Thanks for reporting!
