### ISSUE TITLE
the fastqc "Multiqc" module broke

### ISSUE THREAD

**Issue by georgiatari** [ewels/MultiQC#1696] opened 2022-05-31 14:53 UTC
### Description of bug

 Please attach a file that triggers the error.

### MultiQC Error log

```console
/// MultiQC 🔍 | v1.12

|           multiqc | Search path : /home1/georgiatar/hypoxia/renamed_data
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 570/570
╭────────────────────────────────────────── Oops! The 'fastqc' MultiQC module broke... ──────────────────────────────────────────╮
│ Please copy this log and report it at https://github.com/ewels/MultiQC/issues                                                  │
│ Please attach a file that triggers the error. The last file found was: None                                                    │
│                                                                                                                                │
│ Traceback (most recent call last):                                                                                             │
│   File "/mnt/big/envSW/python/3.7.8/lib/python3.7/site-packages/multiqc/multiqc.py", line 649, in run                          │
│     mod = config.avail_modules[this_module].load()                                                                             │
│   File "/mnt/big/envSW/python/3.7.8/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2462, in load                 │
│     return self.resolve()                                                                                                      │
│   File "/mnt/big/envSW/python/3.7.8/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2468, in resolve              │
│     module = __import__(self.module_name, fromlist=['__name__'], level=0)                                                      │
│   File "/mnt/big/envSW/python/3.7.8/lib/python3.7/site-packages/multiqc/modules/fastqc/__init__.py", line 3, in <module>       │
│     from .fastqc import MultiqcModule                                                                                          │
│   File "/mnt/big/envSW/python/3.7.8/lib/python3.7/site-packages/multiqc/modules/fastqc/fastqc.py", line 25, in <module>        │
│     from multiqc.modules.base_module import BaseMultiqcModule                                                                  │
│   File "/mnt/big/envSW/python/3.7.8/lib/python3.7/site-packages/multiqc/modules/base_module.py", line 10, in <module>          │
│     import markdown                                                                                                            │
│   File "/mnt/big/envSW/python/3.7.8/lib/python3.7/site-packages/markdown/__init__.py", line 29, in <module>                    │
│     from .core import Markdown, markdown, markdownFromFile  # noqa: E402                                                       │
│   File "/mnt/big/envSW/python/3.7.8/lib/python3.7/site-packages/markdown/core.py", line 26, in <module>                        │
│     from . import util                                                                                                         │
│   File "/mnt/big/envSW/python/3.7.8/lib/python3.7/site-packages/markdown/util.py", line 88, in <module>                        │
│     INSTALLED_EXTENSIONS = metadata.entry_points(group='markdown.extensions')                                                  │
│   File "/mnt/big/envSW/python/3.7.8/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 1047, in entry_points    │
│     return SelectableGroups.load(eps).select(**params)                                                                         │
│   File "/mnt/big/envSW/python/3.7.8/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 477, in load             │
│     ordered = sorted(eps, key=by_group)                                                                                        │
│   File "/mnt/big/envSW/python/3.7.8/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 1045, in <genexpr>       │
│     dist.entry_points for dist in _unique(distributions())                                                                     │
│   File "/mnt/big/envSW/python/3.7.8/lib/python3.7/site-packages/importlib_metadata/_itertools.py", line 16, in unique_everseen │
│     k = key(element)                                                                                                           │
│   File "/mnt/big/envSW/python/3.7.8/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 961, in _normalized_name │
│     or super()._normalized_name                                                                                                │
│   File "/mnt/big/envSW/python/3.7.8/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 628, in _normalized_name │
│     return Prepared.normalize(self.name)                                                                                       │
│   File "/mnt/big/envSW/python/3.7.8/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 883, in normalize        │
│     return re.sub(r"[-_.]+", "-", name).lower().replace('-', '_')                                                              │
│   File "/mnt/big/envSW/python/3.7.8/lib/python3.7/re.py", line 194, in sub                                                     │
│     return _compile(pattern, flags).sub(repl, string, count)                                                                   │
│ TypeError: expected string or bytes-like object                                                                                │
│                                                                                                                                │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
|           multiqc | No analysis results found. Cleaning up..
|           multiqc | MultiQC complete
```

**Comment by ewels** [comment] 2022-06-01 10:12
> Please attach a file that triggers the error.

Without this it's very difficult to troubleshoot 👍🏻

**Comment by georgiatari** [comment] 2022-06-01 10:17
Unfortunately, I can't see such a file, it doesn't produce anything..

**Comment by ewels** [comment] 2022-06-01 10:19
Right, but you're running MultiQC with `/home1/georgiatar/hypoxia/renamed_data`. Can you try running MultiQC with a single FastQC report in there to see if you get the same error? If so, attach that FastQC zip file here.

**Comment by georgiatari** [comment] 2022-06-01 10:38
Thats true.. I was just informed by the administrator of the HPC system of my Institute that he managed to complete the job for me, doing the same things as I did, and he doesn't know why.. Yet I want to try to find the problem for future analyses.. I attach a txt file with the output
[output.txt](https://github.com/ewels/MultiQC/files/8813310/output.txt)
.

**Comment by ewels** [comment] 2023-09-23 12:35
Closing, as can't reproduce. Please reopen if this is still a problem!

**Closed by ewels** 2023-09-23 12:35 UTC
