### ISSUE TITLE
Same NanoStat Error as #1663

### ISSUE THREAD

**Issue by reesea22** [ewels/MultiQC#1676] opened 2022-05-06 15:19 UTC
### File that triggers the error

[nanostat.txt](https://github.com/ewels/MultiQC/files/8641682/nanostat.txt)

### MultiQC Error log

```console
$ multiqc -m nanostat .

  /// MultiQC 🔍 | v1.12

|           multiqc | Only using modules: nanostat
|           multiqc | Search path : /home/ont_stats_test
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 6/6  
╭────────────────────────────────────────────────────── Oops! The 'nanostat' MultiQC module broke... ───────────────────────────────────────────────────────╮
│ Please copy this log and report it at https://github.com/ewels/MultiQC/issues                                                                             │
│ Please attach a file that triggers the error. The last file found was: ./nanostat.out                                                                     │
│                                                                                                                                                           │
│ Traceback (most recent call last):                                                                                                                        │
│   File "/home/miniconda3/envs/nanostat/lib/python3.9/site-packages/multiqc/multiqc.py", line 651, in run                                  │
│     output = mod()                                                                                                                                        │
│   File "/home/miniconda3/envs/nanostat/lib/python3.9/site-packages/multiqc/modules/nanostat/nanostat.py", line 63, in __init__            │
│     self.parse_nanostat_log(f)                                                                                                                            │
│   File "/home/miniconda3/envs/nanostat/lib/python3.9/site-packages/multiqc/modules/nanostat/nanostat.py", line 100, in parse_nanostat_log │
│     line = jinja2.escape(line)                                                                                                                            │
│ AttributeError: module 'jinja2' has no attribute 'escape'                                                                                                 │
│                                                                                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
|           multiqc | No analysis results found. Cleaning up..
|           multiqc | MultiQC complete
```

**Comment by ewels** [comment] 2022-05-06 15:45
Ah, duplicate of https://github.com/ewels/MultiQC/pull/1655 - already fixed in https://github.com/ewels/MultiQC/pull/1659

Please run the development version for now, I will be releasing a new version of MultiQC with this fix included soon.

Alternatively, downgrade the `jinja2` library to < 3.1 (3.0 should be fine). That should also solve the issue.

**Closed by ewels** 2022-05-06 15:45 UTC
Labels: priority: high, module: bug
