### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by jrotieno** [ewels/MultiQC#473] opened 2017-06-06 09:17 UTC
I get the segfault error when running multiqc. Any suggestions on solutions?

Command used:

`multiqc -m fastqc ./1_R1_fastqc`

The output and error message:

```
[INFO   ]         multiqc : This is MultiQC v1.0
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching './1_R1_fastqc'
[INFO   ]         multiqc : Only using modules fastqc
Searching 18 files..  [####################################]  100%
Segmentation fault: 11
```

Thanks!

**Comment by epruesse** [comment] 2017-06-07 18:24
What python version are you using?

 - If it's 3.x, try `export PYTHONFAULTHANDLER=1` and rerun your cmd line. That should give a more helpful log.
 - If it's 2.7, installing the `faulthandler` package and putting `import faulthandler; faulthandler.enable()` somewhere at the beginning into the multiqc script (`$ which multiqc`) should do the same.

**Comment by ewels** [comment] 2017-06-08 14:02
Hi @jrotieno,

As asked by @epruesse - more details about your environment and how you installed MultiQC would be helpful.. I've never seen this error before though.

My suspicion after a quick bit of googling is that it will be coming from something strange in a native version of Python on Mac OSX. In these cases I usually recommend using conda if possible (as [described in the docs](http://multiqc.info/docs/#installing-multiqc)). It's often quite a bit quicker than fighting with a native Python installation, and if you're not using the system version of Python you're less likely to break other stuff 💥 

Phil

**Comment by jrotieno** [comment] 2017-06-08 14:55
@epruesse, using Python 2.7 (miniconda installation). I get the output below from faulthandler:

> Searching 557 files..  [####################################]  100%             
Fatal Python error: Segmentation fault

> Current thread 0x00007fffa69193c0 (most recent call first):
  File "/Users/jotieno/miniconda2/lib/python2.7/site-packages/matplotlib/font_manager.py", line 595 in createFontList
  File "/Users/jotieno/miniconda2/lib/python2.7/site-packages/matplotlib/font_manager.py", line 1068 in __init__
  File "/Users/jotieno/miniconda2/lib/python2.7/site-packages/matplotlib/font_manager.py", line 1418 in _rebuild
  File "/Users/jotieno/miniconda2/lib/python2.7/site-packages/matplotlib/font_manager.py", line 1432 in <module>
  File "/Users/jotieno/miniconda2/lib/python2.7/site-packages/matplotlib/contour.py", line 22 in <module>
  File "/Users/jotieno/miniconda2/lib/python2.7/site-packages/matplotlib/colorbar.py", line 36 in <module>
  File "/Users/jotieno/miniconda2/lib/python2.7/site-packages/matplotlib/pyplot.py", line 29 in <module>
  File "/Users/jotieno/miniconda2/lib/python2.7/site-packages/multiqc/plots/linegraph.py", line 21 in <module>
  File "/Users/jotieno/miniconda2/lib/python2.7/site-packages/multiqc/modules/fastqc/fastqc.py", line 23 in <module>
  File "/Users/jotieno/miniconda2/lib/python2.7/site-packages/multiqc/modules/fastqc/__init__.py", line 3 in <module>
  File "/Users/jotieno/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2309 in resolve
  File "/Users/jotieno/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2303 in load
  File "/Users/jotieno/miniconda2/bin/multiqc", line 372 in multiqc
  File "/Users/jotieno/miniconda2/lib/python2.7/site-packages/click/core.py", line 535 in invoke
  File "/Users/jotieno/miniconda2/lib/python2.7/site-packages/click/core.py", line 895 in invoke
  File "/Users/jotieno/miniconda2/lib/python2.7/site-packages/click/core.py", line 697 in main
  File "/Users/jotieno/miniconda2/lib/python2.7/site-packages/click/core.py", line 722 in __call__
  File "/Users/jotieno/miniconda2/bin/multiqc", line 640 in <module>
Segmentation fault: 11


@ewels, I installed multiqc using `pip install multiqc`

Just uninstalled then re-installed with condo, same error as above.
Would a manual install help?

James

**Comment by ewels** [comment] 2017-06-08 15:05
Thanks for the extra info. To reinstall you probably need the `--upgrade` and `--force-reinstall` flags, otherwise `pip` doesn't do anything. eg:

```
pip install --upgrade --force-reinstall multiqc
```

It's probably also worth trying to force a reinstallation of matplotlib, as that seems to be the code that's triggering the error (matplotlib accounts for ~90% of MultiQC installation problems). Same command as above but with `matplotlib` instead of `multiqc`.

I'm not 100% sure what happens if you install a package into a conda environment using a conda install after it's already been installed with `pip`. What happens if you try with a totally blank environment? eg. something like:

```
conda create --name mqc_env python=2.7 pip matplotlib multiqc
source activate mqc_env
multiqc -m fastqc ./1_R1_fastqc
```

Phil

**Comment by jrotieno** [comment] 2017-06-08 15:17
@ewels, did the forced re-install for both multiqc and matplotlib and got the same errors as before.

Also created the conda environment, activated and ran multiqc and got the error below

> Traceback (most recent call last):
  File "/Users/jotieno/miniconda2/envs/mqc_env/bin/multiqc", line 4, in <module>
    __import__('pkg_resources').run_script('multiqc==1.0', 'multiqc')
  File "/Users/jotieno/miniconda2/envs/mqc_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/jotieno/miniconda2/envs/mqc_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1494, in run_script
    exec(code, namespace, namespace)
  File "/Users/jotieno/miniconda2/envs/mqc_env/lib/python2.7/site-packages/multiqc-1.0-py2.7.egg/EGG-INFO/scripts/multiqc", line 32, in <module>
    from multiqc.plots import table
  File "/Users/jotieno/miniconda2/envs/mqc_env/lib/python2.7/site-packages/multiqc-1.0-py2.7.egg/multiqc/plots/table.py", line 9, in <module>
    from multiqc.utils import config, report, util_functions, mqc_colour
  File "/Users/jotieno/miniconda2/envs/mqc_env/lib/python2.7/site-packages/multiqc-1.0-py2.7.egg/multiqc/utils/mqc_colour.py", line 7, in <module>
    import spectra
  File "/Users/jotieno/miniconda2/envs/mqc_env/lib/python2.7/site-packages/spectra/__init__.py", line 1, in <module>
    from spectra.core import COLOR_SPACES, Color, Scale
  File "/Users/jotieno/miniconda2/envs/mqc_env/lib/python2.7/site-packages/spectra/core.py", line 1, in <module>
    from colormath import color_objects, color_conversions
  File "/Users/jotieno/miniconda2/envs/mqc_env/lib/python2.7/site-packages/colormath/color_objects.py", line 8, in <module>
    import numpy
  File "/Users/jotieno/miniconda2/envs/mqc_env/lib/python2.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/Users/jotieno/miniconda2/envs/mqc_env/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/Users/jotieno/miniconda2/envs/mqc_env/lib/python2.7/site-packages/numpy/lib/__init__.py", line 11, in <module>
    from .mixins import *
ImportError: No module named mixins

What baffles me is that, I have absolutely no problems running multiqc on my MacBook Pro (the errors above are on a MacPro, but same OS Sierra).

James

**Comment by ewels** [comment] 2017-06-08 15:35
Super strange - this new error looks totally different 😕  What on earth is going on?! 😆 

Ok - new conda environment, what happens if you try installing MultiQC version 0.9? `multiqc==0.9`. Need to go home now, will keep thinking.. Do you run any other Python programs on this machine?

Phil

**Comment by ewels** [comment] 2017-06-28 10:05
Hi @jrotieno,

Did you make any progress with this problem?

Phil

**Comment by jrotieno** [comment] 2017-06-28 10:46
Hi @ewels,

Unfortunately, No. Still getting the `Segmentation fault: 11` error.

I did another force re-install for v1.0 and install for v0.9 when I got your message but same problem.

James

**Comment by epruesse** [comment] 2017-06-28 19:57
Generally, when you get segmentation faults, try re-running the command line prefixed with `catchsegv` or exporting "LD_PRELOAD=/lib/libSegFault.so". That should give you a more helpful output than "it crashed".

@ewels: It might be useful to just add [`faulthandler`](http://faulthandler.readthedocs.io/) to multiqc. It doesn't cost much in performance (basically just the ms to load it) and improves the data you get in case of crashes.

**Comment by ewels** [comment] 2017-06-29 08:28
Thanks for the suggestion @epruesse - looks nice! Kind of difficult for me to test though :D

@jrderuiter - I've just added this package into a branch. Could you try installing and running that please and see if we get more useful output?

```
pip install --upgrade --force-reinstall git+https://github.com/ewels/MultiQC.git@faulthandler
```

**Comment by jrderuiter** [comment] 2017-06-29 08:39
I can't reproduce this on my machine (Sierra, using miniconda3 with Python 2.7).

```
[INFO   ]         multiqc : This is MultiQC v1.1.dev0
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching '.'
[INFO   ]         multiqc : Only using modules fastqc
Searching 9 files..  [####################################]  100%
[INFO   ]          fastqc : Found 1 reports
[INFO   ]         multiqc : Compressing plot data
[INFO   ]         multiqc : Report      : multiqc_report.html
[INFO   ]         multiqc : Data        : multiqc_data
[INFO   ]         multiqc : MultiQC complete
```

**Comment by jrotieno** [comment] 2017-06-29 08:43
@epruesse : I had actually installed `fault handler` as earlier advised and posted the error above.

@ewels : I also just did the same install as @jrderuiter (also on Sierra, but using miniconda2 with Python 2.7) and getting below:
```
multiqc -m fastqc ./*/raw
[INFO   ]         multiqc : This is MultiQC v1.1.dev0
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching './1/raw'
[INFO   ]         multiqc : Searching './12/raw'
[INFO   ]         multiqc : Searching './14/raw'
[INFO   ]         multiqc : Searching './16/raw'
[INFO   ]         multiqc : Searching './17/raw'
[INFO   ]         multiqc : Searching './18/raw'
[INFO   ]         multiqc : Searching './2/raw'
[INFO   ]         multiqc : Searching './3/raw'
[INFO   ]         multiqc : Searching './34/raw'
[INFO   ]         multiqc : Searching './35/raw'
[INFO   ]         multiqc : Searching './36/raw'
[INFO   ]         multiqc : Searching './38/raw'
[INFO   ]         multiqc : Searching './39/raw'
[INFO   ]         multiqc : Searching './4/raw'
[INFO   ]         multiqc : Searching './40/raw'
[INFO   ]         multiqc : Searching './41/raw'
[INFO   ]         multiqc : Searching './42/raw'
[INFO   ]         multiqc : Searching './43/raw'
[INFO   ]         multiqc : Searching './44/raw'
[INFO   ]         multiqc : Searching './45/raw'
[INFO   ]         multiqc : Searching './46/raw'
[INFO   ]         multiqc : Searching './47/raw'
[INFO   ]         multiqc : Searching './48/raw'
[INFO   ]         multiqc : Searching './49/raw'
[INFO   ]         multiqc : Searching './5/raw'
[INFO   ]         multiqc : Searching './54/raw'
[INFO   ]         multiqc : Searching './56/raw'
[INFO   ]         multiqc : Searching './6/raw'
[INFO   ]         multiqc : Searching './7/raw'
[INFO   ]         multiqc : Searching './8/raw'
[INFO   ]         multiqc : Searching './9/raw'
[INFO   ]         multiqc : Only using modules fastqc
Searching 557 files..  [####################################]  100%             
Fatal Python error: Segmentation fault

Current thread 0x00007fffc02e73c0 (most recent call first):
  File "/Users/jotieno/miniconda2/lib/python2.7/site-packages/matplotlib/font_manager.py", line 595 in createFontList
  File "/Users/jotieno/miniconda2/lib/python2.7/site-packages/matplotlib/font_manager.py", line 1068 in __init__
  File "/Users/jotieno/miniconda2/lib/python2.7/site-packages/matplotlib/font_manager.py", line 1418 in _rebuild
  File "/Users/jotieno/miniconda2/lib/python2.7/site-packages/matplotlib/font_manager.py", line 1432 in <module>
  File "/Users/jotieno/miniconda2/lib/python2.7/site-packages/matplotlib/contour.py", line 22 in <module>
  File "/Users/jotieno/miniconda2/lib/python2.7/site-packages/matplotlib/colorbar.py", line 36 in <module>
  File "/Users/jotieno/miniconda2/lib/python2.7/site-packages/matplotlib/pyplot.py", line 29 in <module>
  File "/Users/jotieno/miniconda2/lib/python2.7/site-packages/multiqc/plots/linegraph.py", line 21 in <module>
  File "/Users/jotieno/miniconda2/lib/python2.7/site-packages/multiqc/modules/fastqc/fastqc.py", line 23 in <module>
  File "/Users/jotieno/miniconda2/lib/python2.7/site-packages/multiqc/modules/fastqc/__init__.py", line 3 in <module>
  File "/Users/jotieno/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2297 in resolve
  File "/Users/jotieno/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2291 in load
  File "/Users/jotieno/miniconda2/bin/multiqc", line 375 in multiqc
  File "/Users/jotieno/miniconda2/lib/python2.7/site-packages/click/core.py", line 535 in invoke
  File "/Users/jotieno/miniconda2/lib/python2.7/site-packages/click/core.py", line 895 in invoke
  File "/Users/jotieno/miniconda2/lib/python2.7/site-packages/click/core.py", line 697 in main
  File "/Users/jotieno/miniconda2/lib/python2.7/site-packages/click/core.py", line 722 in __call__
  File "/Users/jotieno/miniconda2/bin/multiqc", line 643 in <module>
Segmentation fault: 11

```

**Comment by ewels** [comment] 2017-06-29 08:43
Ooh, apologies @jrderuiter! I tagged the wrong GitHub handle! I meant @jrotieno (the OP).

Thanks for testing anyway though! 😇

**Comment by jrderuiter** [comment] 2017-06-29 08:43
Ok, I didn't quite understand why you included me ;)

**Comment by jrotieno** [comment] 2017-06-29 08:44
I had a hunch it was meant for me though @ewels :)

**Comment by ewels** [comment] 2017-06-29 08:51
Also apologies for not realising that you'd already done this @jrotieno. I'm still at a complete loss from this - the traceback points the finger at the MatPlotLib dependency, but why it's throwing that error is a mystery. Googling similar errors gives a bunch of other GitHub issues with equally confused people, nearly all closed without being resolved. It sounds highly likely that it's a system-specific problem and essentially not anything that I'm going to be able to affect or help you with 😞 

The only (highly unsatisfying) advice I can think of is to try installing a totally fresh copy of Python which is as separate from your existing conda installation as possible. Or perhaps format your hard disk and start with a fresh OS install?? 😂  

Either way, I'll close this issue now as I don't think that there's anything that I can do. Please feel free to comment / reopen if there are any new hints or you make any progress.

**Closed by ewels** 2017-06-29 08:51 UTC
Labels: bug

**Comment by ewels** [comment] 2017-06-29 08:54
ps. @epruesse - looks like `faulthandler` [doesn't](https://travis-ci.org/ewels/MultiQC/builds/248276011) [support](http://faulthandler.readthedocs.io/#installation) Python3. So unfortunately that's a no go. Thanks for the tip though, I will keep that in mind for future projects as it seems like a nice tool!

**Comment by jrotieno** [comment] 2017-06-29 08:55
@ewels , No worries absolutely, it does work on my MacBook so will use that installation instead of the problematic one not the MacPro.
Should I get it working, you'll be promptly updated!
